package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.Chanqiansuifangjilu01;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHANQIANSUIFANGJILU01".
*/
public class Chanqiansuifangjilu01Dao extends AbstractDao<Chanqiansuifangjilu01, Long> {

    public static final String TABLENAME = "CHANQIANSUIFANGJILU01";

    /**
     * Properties of entity Chanqiansuifangjilu01.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Ycf_id = new Property(1, String.class, "ycf_id", false, "YCF_ID");
        public final static Property Na_id = new Property(2, String.class, "na_id", false, "NA_ID");
        public final static Property Ycf_date = new Property(3, String.class, "ycf_date", false, "YCF_DATE");
        public final static Property Ycf_week = new Property(4, int.class, "ycf_week", false, "YCF_WEEK");
        public final static Property Ycf_age = new Property(5, int.class, "ycf_age", false, "YCF_AGE");
        public final static Property Ycf_man_name = new Property(6, String.class, "ycf_man_name", false, "YCF_MAN_NAME");
        public final static Property Ycf_man_age = new Property(7, int.class, "ycf_man_age", false, "YCF_MAN_AGE");
        public final static Property Ycf_man_tel = new Property(8, String.class, "ycf_man_tel", false, "YCF_MAN_TEL");
        public final static Property Ycf_number = new Property(9, int.class, "ycf_number", false, "YCF_NUMBER");
        public final static Property Ycf_fm = new Property(10, int.class, "ycf_fm", false, "YCF_FM");
        public final static Property Ycf_pfc = new Property(11, int.class, "ycf_pfc", false, "YCF_PFC");
        public final static Property Ycf_mcyj = new Property(12, String.class, "ycf_mcyj", false, "YCF_MCYJ");
        public final static Property Ycf_ycq = new Property(13, String.class, "ycf_ycq", false, "YCF_YCQ");
        public final static Property Ycf_jws = new Property(14, int.class, "ycf_jws", false, "YCF_JWS");
        public final static Property Ycf_jzs = new Property(15, int.class, "ycf_jzs", false, "YCF_JZS");
        public final static Property Ycf__grs = new Property(16, int.class, "ycf__grs", false, "YCF__GRS");
        public final static Property Ycf_fkss = new Property(17, int.class, "ycf_fkss", false, "YCF_FKSS");
        public final static Property Ycf_fkss_details = new Property(18, String.class, "ycf_fkss_details", false, "YCF_FKSS_DETAILS");
        public final static Property Ycf_liuc = new Property(19, String.class, "ycf_liuc", false, "YCF_LIUC");
        public final static Property Ycf_sit = new Property(20, String.class, "ycf_sit", false, "YCF_SIT");
        public final static Property Ycf_shunc = new Property(21, String.class, "ycf_shunc", false, "YCF_SHUNC");
        public final static Property Ycf_xssw = new Property(22, String.class, "ycf_xssw", false, "YCF_XSSW");
        public final static Property Ycf_csqx = new Property(23, String.class, "ycf_csqx", false, "YCF_CSQX");
        public final static Property Hw_id = new Property(24, String.class, "hw_id", false, "HW_ID");
        public final static Property Bp_id = new Property(25, String.class, "bp_id", false, "BP_ID");
        public final static Property Ycf_xz = new Property(26, int.class, "ycf_xz", false, "YCF_XZ");
        public final static Property Ycf_xz_details = new Property(27, String.class, "ycf_xz_details", false, "YCF_XZ_DETAILS");
        public final static Property Ycf_fei = new Property(28, int.class, "ycf_fei", false, "YCF_FEI");
        public final static Property Ycf_fei_details = new Property(29, String.class, "ycf_fei_details", false, "YCF_FEI_DETAILS");
        public final static Property Ycf_wy = new Property(30, int.class, "ycf_wy", false, "YCF_WY");
        public final static Property Ycf_wy_details = new Property(31, String.class, "ycf_wy_details", false, "YCF_WY_DETAILS");
        public final static Property Ycf_yd = new Property(32, int.class, "ycf_yd", false, "YCF_YD");
        public final static Property Ycf_yd_details = new Property(33, String.class, "ycf_yd_details", false, "YCF_YD_DETAILS");
        public final static Property Ycf_gj = new Property(34, int.class, "ycf_gj", false, "YCF_GJ");
        public final static Property Ycf_gj_details = new Property(35, String.class, "ycf_gj_details", false, "YCF_GJ_DETAILS");
        public final static Property Ycf_zg = new Property(36, int.class, "ycf_zg", false, "YCF_ZG");
        public final static Property Ycf_zg_details = new Property(37, String.class, "ycf_zg_details", false, "YCF_ZG_DETAILS");
        public final static Property Ycf_fj = new Property(38, int.class, "ycf_fj", false, "YCF_FJ");
        public final static Property Ycf_fj_details = new Property(39, String.class, "ycf_fj_details", false, "YCF_FJ_DETAILS");
        public final static Property Ycf_xhdb = new Property(40, String.class, "ycf_xhdb", false, "YCF_XHDB");
        public final static Property Ycf_bxb = new Property(41, String.class, "ycf_bxb", false, "YCF_BXB");
        public final static Property Ycf_xxb = new Property(42, String.class, "ycf_xxb", false, "YCF_XXB");
        public final static Property Ycf_xqt = new Property(43, String.class, "ycf_xqt", false, "YCF_XQT");
        public final static Property Ycf_ndb = new Property(44, String.class, "ycf_ndb", false, "YCF_NDB");
        public final static Property Ycf_ntt = new Property(45, String.class, "ycf_ntt", false, "YCF_NTT");
        public final static Property Ycf_nt = new Property(46, String.class, "ycf_nt", false, "YCF_NT");
        public final static Property Ycf_nqx = new Property(47, String.class, "ycf_nqx", false, "YCF_NQX");
        public final static Property Ycf_nqt = new Property(48, String.class, "ycf_nqt", false, "YCF_NQT");
        public final static Property Ycf_fz_xx = new Property(49, String.class, "ycf_fz_xx", false, "YCF_FZ_XX");
        public final static Property Ycf_fz_rh = new Property(50, String.class, "ycf_fz_rh", false, "YCF_FZ_RH");
        public final static Property Ycf_fz_xt = new Property(51, String.class, "ycf_fz_xt", false, "YCF_FZ_XT");
        public final static Property Ycf_fz_fmw = new Property(52, int.class, "ycf_fz_fmw", false, "YCF_FZ_FMW");
        public final static Property Ycf_fz_qjd = new Property(53, int.class, "ycf_fz_qjd", false, "YCF_FZ_QJD");
        public final static Property Ycf_gan_xqgb = new Property(54, String.class, "ycf_gan_xqgb", false, "YCF_GAN_XQGB");
        public final static Property Ycf_gan_xqgc = new Property(55, String.class, "ycf_gan_xqgc", false, "YCF_GAN_XQGC");
        public final static Property Ycf_gan_bdb = new Property(56, String.class, "ycf_gan_bdb", false, "YCF_GAN_BDB");
        public final static Property Ycf_gan_zdhs = new Property(57, String.class, "ycf_gan_zdhs", false, "YCF_GAN_ZDHS");
        public final static Property Ycf_gan_jhdhs = new Property(58, String.class, "ycf_gan_jhdhs", false, "YCF_GAN_JHDHS");
        public final static Property Ycf_shen_xq = new Property(59, String.class, "ycf_shen_xq", false, "YCF_SHEN_XQ");
        public final static Property Ycf_shen_xn = new Property(60, String.class, "ycf_shen_xn", false, "YCF_SHEN_XN");
        public final static Property Ycf_yg_bmky = new Property(61, String.class, "ycf_yg_bmky", false, "YCF_YG_BMKY");
        public final static Property Ycf_yg_bmkt = new Property(62, String.class, "ycf_yg_bmkt", false, "YCF_YG_BMKT");
        public final static Property Ycf_yg_eky = new Property(63, String.class, "ycf_yg_eky", false, "YCF_YG_EKY");
        public final static Property Ycf_yg_ekt = new Property(64, String.class, "ycf_yg_ekt", false, "YCF_YG_EKT");
        public final static Property Ycf_yg_hxkt = new Property(65, String.class, "ycf_yg_hxkt", false, "YCF_YG_HXKT");
        public final static Property Ycf_fz_mdxq = new Property(66, int.class, "ycf_fz_mdxq", false, "YCF_FZ_MDXQ");
        public final static Property Ycf_fz_hv = new Property(67, int.class, "ycf_fz_hv", false, "YCF_FZ_HV");
        public final static Property Ycf_fz_bc = new Property(68, String.class, "ycf_fz_bc", false, "YCF_FZ_BC");
        public final static Property Ycf_ztpg = new Property(69, int.class, "ycf_ztpg", false, "YCF_ZTPG");
        public final static Property Ycf_zt_details = new Property(70, String.class, "ycf_zt_details", false, "YCF_ZT_DETAILS");
        public final static Property Ycf_bjzd = new Property(71, String.class, "ycf_bjzd", false, "YCF_BJZD");
        public final static Property Ycf_zz = new Property(72, String.class, "ycf_zz", false, "YCF_ZZ");
        public final static Property Ycf_yy = new Property(73, String.class, "ycf_yy", false, "YCF_YY");
        public final static Property Ycf_jg = new Property(74, String.class, "ycf_jg", false, "YCF_JG");
        public final static Property Ycf_nextdate = new Property(75, String.class, "ycf_nextdate", false, "YCF_NEXTDATE");
        public final static Property Ycf_doctor = new Property(76, String.class, "ycf_doctor", false, "YCF_DOCTOR");
        public final static Property CreateDate = new Property(77, String.class, "createDate", false, "CREATE_DATE");
    }


    public Chanqiansuifangjilu01Dao(DaoConfig config) {
        super(config);
    }
    
    public Chanqiansuifangjilu01Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHANQIANSUIFANGJILU01\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"YCF_ID\" TEXT NOT NULL ," + // 1: ycf_id
                "\"NA_ID\" TEXT NOT NULL ," + // 2: na_id
                "\"YCF_DATE\" TEXT," + // 3: ycf_date
                "\"YCF_WEEK\" INTEGER NOT NULL ," + // 4: ycf_week
                "\"YCF_AGE\" INTEGER NOT NULL ," + // 5: ycf_age
                "\"YCF_MAN_NAME\" TEXT," + // 6: ycf_man_name
                "\"YCF_MAN_AGE\" INTEGER NOT NULL ," + // 7: ycf_man_age
                "\"YCF_MAN_TEL\" TEXT," + // 8: ycf_man_tel
                "\"YCF_NUMBER\" INTEGER NOT NULL ," + // 9: ycf_number
                "\"YCF_FM\" INTEGER NOT NULL ," + // 10: ycf_fm
                "\"YCF_PFC\" INTEGER NOT NULL ," + // 11: ycf_pfc
                "\"YCF_MCYJ\" TEXT," + // 12: ycf_mcyj
                "\"YCF_YCQ\" TEXT," + // 13: ycf_ycq
                "\"YCF_JWS\" INTEGER NOT NULL ," + // 14: ycf_jws
                "\"YCF_JZS\" INTEGER NOT NULL ," + // 15: ycf_jzs
                "\"YCF__GRS\" INTEGER NOT NULL ," + // 16: ycf__grs
                "\"YCF_FKSS\" INTEGER NOT NULL ," + // 17: ycf_fkss
                "\"YCF_FKSS_DETAILS\" TEXT," + // 18: ycf_fkss_details
                "\"YCF_LIUC\" TEXT," + // 19: ycf_liuc
                "\"YCF_SIT\" TEXT," + // 20: ycf_sit
                "\"YCF_SHUNC\" TEXT," + // 21: ycf_shunc
                "\"YCF_XSSW\" TEXT," + // 22: ycf_xssw
                "\"YCF_CSQX\" TEXT," + // 23: ycf_csqx
                "\"HW_ID\" TEXT," + // 24: hw_id
                "\"BP_ID\" TEXT," + // 25: bp_id
                "\"YCF_XZ\" INTEGER NOT NULL ," + // 26: ycf_xz
                "\"YCF_XZ_DETAILS\" TEXT," + // 27: ycf_xz_details
                "\"YCF_FEI\" INTEGER NOT NULL ," + // 28: ycf_fei
                "\"YCF_FEI_DETAILS\" TEXT," + // 29: ycf_fei_details
                "\"YCF_WY\" INTEGER NOT NULL ," + // 30: ycf_wy
                "\"YCF_WY_DETAILS\" TEXT," + // 31: ycf_wy_details
                "\"YCF_YD\" INTEGER NOT NULL ," + // 32: ycf_yd
                "\"YCF_YD_DETAILS\" TEXT," + // 33: ycf_yd_details
                "\"YCF_GJ\" INTEGER NOT NULL ," + // 34: ycf_gj
                "\"YCF_GJ_DETAILS\" TEXT," + // 35: ycf_gj_details
                "\"YCF_ZG\" INTEGER NOT NULL ," + // 36: ycf_zg
                "\"YCF_ZG_DETAILS\" TEXT," + // 37: ycf_zg_details
                "\"YCF_FJ\" INTEGER NOT NULL ," + // 38: ycf_fj
                "\"YCF_FJ_DETAILS\" TEXT," + // 39: ycf_fj_details
                "\"YCF_XHDB\" TEXT," + // 40: ycf_xhdb
                "\"YCF_BXB\" TEXT," + // 41: ycf_bxb
                "\"YCF_XXB\" TEXT," + // 42: ycf_xxb
                "\"YCF_XQT\" TEXT," + // 43: ycf_xqt
                "\"YCF_NDB\" TEXT," + // 44: ycf_ndb
                "\"YCF_NTT\" TEXT," + // 45: ycf_ntt
                "\"YCF_NT\" TEXT," + // 46: ycf_nt
                "\"YCF_NQX\" TEXT," + // 47: ycf_nqx
                "\"YCF_NQT\" TEXT," + // 48: ycf_nqt
                "\"YCF_FZ_XX\" TEXT," + // 49: ycf_fz_xx
                "\"YCF_FZ_RH\" TEXT," + // 50: ycf_fz_rh
                "\"YCF_FZ_XT\" TEXT," + // 51: ycf_fz_xt
                "\"YCF_FZ_FMW\" INTEGER NOT NULL ," + // 52: ycf_fz_fmw
                "\"YCF_FZ_QJD\" INTEGER NOT NULL ," + // 53: ycf_fz_qjd
                "\"YCF_GAN_XQGB\" TEXT," + // 54: ycf_gan_xqgb
                "\"YCF_GAN_XQGC\" TEXT," + // 55: ycf_gan_xqgc
                "\"YCF_GAN_BDB\" TEXT," + // 56: ycf_gan_bdb
                "\"YCF_GAN_ZDHS\" TEXT," + // 57: ycf_gan_zdhs
                "\"YCF_GAN_JHDHS\" TEXT," + // 58: ycf_gan_jhdhs
                "\"YCF_SHEN_XQ\" TEXT," + // 59: ycf_shen_xq
                "\"YCF_SHEN_XN\" TEXT," + // 60: ycf_shen_xn
                "\"YCF_YG_BMKY\" TEXT," + // 61: ycf_yg_bmky
                "\"YCF_YG_BMKT\" TEXT," + // 62: ycf_yg_bmkt
                "\"YCF_YG_EKY\" TEXT," + // 63: ycf_yg_eky
                "\"YCF_YG_EKT\" TEXT," + // 64: ycf_yg_ekt
                "\"YCF_YG_HXKT\" TEXT," + // 65: ycf_yg_hxkt
                "\"YCF_FZ_MDXQ\" INTEGER NOT NULL ," + // 66: ycf_fz_mdxq
                "\"YCF_FZ_HV\" INTEGER NOT NULL ," + // 67: ycf_fz_hv
                "\"YCF_FZ_BC\" TEXT," + // 68: ycf_fz_bc
                "\"YCF_ZTPG\" INTEGER NOT NULL ," + // 69: ycf_ztpg
                "\"YCF_ZT_DETAILS\" TEXT," + // 70: ycf_zt_details
                "\"YCF_BJZD\" TEXT," + // 71: ycf_bjzd
                "\"YCF_ZZ\" TEXT," + // 72: ycf_zz
                "\"YCF_YY\" TEXT," + // 73: ycf_yy
                "\"YCF_JG\" TEXT," + // 74: ycf_jg
                "\"YCF_NEXTDATE\" TEXT," + // 75: ycf_nextdate
                "\"YCF_DOCTOR\" TEXT," + // 76: ycf_doctor
                "\"CREATE_DATE\" TEXT);"); // 77: createDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHANQIANSUIFANGJILU01\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Chanqiansuifangjilu01 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getYcf_id());
        stmt.bindString(3, entity.getNa_id());
 
        String ycf_date = entity.getYcf_date();
        if (ycf_date != null) {
            stmt.bindString(4, ycf_date);
        }
        stmt.bindLong(5, entity.getYcf_week());
        stmt.bindLong(6, entity.getYcf_age());
 
        String ycf_man_name = entity.getYcf_man_name();
        if (ycf_man_name != null) {
            stmt.bindString(7, ycf_man_name);
        }
        stmt.bindLong(8, entity.getYcf_man_age());
 
        String ycf_man_tel = entity.getYcf_man_tel();
        if (ycf_man_tel != null) {
            stmt.bindString(9, ycf_man_tel);
        }
        stmt.bindLong(10, entity.getYcf_number());
        stmt.bindLong(11, entity.getYcf_fm());
        stmt.bindLong(12, entity.getYcf_pfc());
 
        String ycf_mcyj = entity.getYcf_mcyj();
        if (ycf_mcyj != null) {
            stmt.bindString(13, ycf_mcyj);
        }
 
        String ycf_ycq = entity.getYcf_ycq();
        if (ycf_ycq != null) {
            stmt.bindString(14, ycf_ycq);
        }
        stmt.bindLong(15, entity.getYcf_jws());
        stmt.bindLong(16, entity.getYcf_jzs());
        stmt.bindLong(17, entity.getYcf__grs());
        stmt.bindLong(18, entity.getYcf_fkss());
 
        String ycf_fkss_details = entity.getYcf_fkss_details();
        if (ycf_fkss_details != null) {
            stmt.bindString(19, ycf_fkss_details);
        }
 
        String ycf_liuc = entity.getYcf_liuc();
        if (ycf_liuc != null) {
            stmt.bindString(20, ycf_liuc);
        }
 
        String ycf_sit = entity.getYcf_sit();
        if (ycf_sit != null) {
            stmt.bindString(21, ycf_sit);
        }
 
        String ycf_shunc = entity.getYcf_shunc();
        if (ycf_shunc != null) {
            stmt.bindString(22, ycf_shunc);
        }
 
        String ycf_xssw = entity.getYcf_xssw();
        if (ycf_xssw != null) {
            stmt.bindString(23, ycf_xssw);
        }
 
        String ycf_csqx = entity.getYcf_csqx();
        if (ycf_csqx != null) {
            stmt.bindString(24, ycf_csqx);
        }
 
        String hw_id = entity.getHw_id();
        if (hw_id != null) {
            stmt.bindString(25, hw_id);
        }
 
        String bp_id = entity.getBp_id();
        if (bp_id != null) {
            stmt.bindString(26, bp_id);
        }
        stmt.bindLong(27, entity.getYcf_xz());
 
        String ycf_xz_details = entity.getYcf_xz_details();
        if (ycf_xz_details != null) {
            stmt.bindString(28, ycf_xz_details);
        }
        stmt.bindLong(29, entity.getYcf_fei());
 
        String ycf_fei_details = entity.getYcf_fei_details();
        if (ycf_fei_details != null) {
            stmt.bindString(30, ycf_fei_details);
        }
        stmt.bindLong(31, entity.getYcf_wy());
 
        String ycf_wy_details = entity.getYcf_wy_details();
        if (ycf_wy_details != null) {
            stmt.bindString(32, ycf_wy_details);
        }
        stmt.bindLong(33, entity.getYcf_yd());
 
        String ycf_yd_details = entity.getYcf_yd_details();
        if (ycf_yd_details != null) {
            stmt.bindString(34, ycf_yd_details);
        }
        stmt.bindLong(35, entity.getYcf_gj());
 
        String ycf_gj_details = entity.getYcf_gj_details();
        if (ycf_gj_details != null) {
            stmt.bindString(36, ycf_gj_details);
        }
        stmt.bindLong(37, entity.getYcf_zg());
 
        String ycf_zg_details = entity.getYcf_zg_details();
        if (ycf_zg_details != null) {
            stmt.bindString(38, ycf_zg_details);
        }
        stmt.bindLong(39, entity.getYcf_fj());
 
        String ycf_fj_details = entity.getYcf_fj_details();
        if (ycf_fj_details != null) {
            stmt.bindString(40, ycf_fj_details);
        }
 
        String ycf_xhdb = entity.getYcf_xhdb();
        if (ycf_xhdb != null) {
            stmt.bindString(41, ycf_xhdb);
        }
 
        String ycf_bxb = entity.getYcf_bxb();
        if (ycf_bxb != null) {
            stmt.bindString(42, ycf_bxb);
        }
 
        String ycf_xxb = entity.getYcf_xxb();
        if (ycf_xxb != null) {
            stmt.bindString(43, ycf_xxb);
        }
 
        String ycf_xqt = entity.getYcf_xqt();
        if (ycf_xqt != null) {
            stmt.bindString(44, ycf_xqt);
        }
 
        String ycf_ndb = entity.getYcf_ndb();
        if (ycf_ndb != null) {
            stmt.bindString(45, ycf_ndb);
        }
 
        String ycf_ntt = entity.getYcf_ntt();
        if (ycf_ntt != null) {
            stmt.bindString(46, ycf_ntt);
        }
 
        String ycf_nt = entity.getYcf_nt();
        if (ycf_nt != null) {
            stmt.bindString(47, ycf_nt);
        }
 
        String ycf_nqx = entity.getYcf_nqx();
        if (ycf_nqx != null) {
            stmt.bindString(48, ycf_nqx);
        }
 
        String ycf_nqt = entity.getYcf_nqt();
        if (ycf_nqt != null) {
            stmt.bindString(49, ycf_nqt);
        }
 
        String ycf_fz_xx = entity.getYcf_fz_xx();
        if (ycf_fz_xx != null) {
            stmt.bindString(50, ycf_fz_xx);
        }
 
        String ycf_fz_rh = entity.getYcf_fz_rh();
        if (ycf_fz_rh != null) {
            stmt.bindString(51, ycf_fz_rh);
        }
 
        String ycf_fz_xt = entity.getYcf_fz_xt();
        if (ycf_fz_xt != null) {
            stmt.bindString(52, ycf_fz_xt);
        }
        stmt.bindLong(53, entity.getYcf_fz_fmw());
        stmt.bindLong(54, entity.getYcf_fz_qjd());
 
        String ycf_gan_xqgb = entity.getYcf_gan_xqgb();
        if (ycf_gan_xqgb != null) {
            stmt.bindString(55, ycf_gan_xqgb);
        }
 
        String ycf_gan_xqgc = entity.getYcf_gan_xqgc();
        if (ycf_gan_xqgc != null) {
            stmt.bindString(56, ycf_gan_xqgc);
        }
 
        String ycf_gan_bdb = entity.getYcf_gan_bdb();
        if (ycf_gan_bdb != null) {
            stmt.bindString(57, ycf_gan_bdb);
        }
 
        String ycf_gan_zdhs = entity.getYcf_gan_zdhs();
        if (ycf_gan_zdhs != null) {
            stmt.bindString(58, ycf_gan_zdhs);
        }
 
        String ycf_gan_jhdhs = entity.getYcf_gan_jhdhs();
        if (ycf_gan_jhdhs != null) {
            stmt.bindString(59, ycf_gan_jhdhs);
        }
 
        String ycf_shen_xq = entity.getYcf_shen_xq();
        if (ycf_shen_xq != null) {
            stmt.bindString(60, ycf_shen_xq);
        }
 
        String ycf_shen_xn = entity.getYcf_shen_xn();
        if (ycf_shen_xn != null) {
            stmt.bindString(61, ycf_shen_xn);
        }
 
        String ycf_yg_bmky = entity.getYcf_yg_bmky();
        if (ycf_yg_bmky != null) {
            stmt.bindString(62, ycf_yg_bmky);
        }
 
        String ycf_yg_bmkt = entity.getYcf_yg_bmkt();
        if (ycf_yg_bmkt != null) {
            stmt.bindString(63, ycf_yg_bmkt);
        }
 
        String ycf_yg_eky = entity.getYcf_yg_eky();
        if (ycf_yg_eky != null) {
            stmt.bindString(64, ycf_yg_eky);
        }
 
        String ycf_yg_ekt = entity.getYcf_yg_ekt();
        if (ycf_yg_ekt != null) {
            stmt.bindString(65, ycf_yg_ekt);
        }
 
        String ycf_yg_hxkt = entity.getYcf_yg_hxkt();
        if (ycf_yg_hxkt != null) {
            stmt.bindString(66, ycf_yg_hxkt);
        }
        stmt.bindLong(67, entity.getYcf_fz_mdxq());
        stmt.bindLong(68, entity.getYcf_fz_hv());
 
        String ycf_fz_bc = entity.getYcf_fz_bc();
        if (ycf_fz_bc != null) {
            stmt.bindString(69, ycf_fz_bc);
        }
        stmt.bindLong(70, entity.getYcf_ztpg());
 
        String ycf_zt_details = entity.getYcf_zt_details();
        if (ycf_zt_details != null) {
            stmt.bindString(71, ycf_zt_details);
        }
 
        String ycf_bjzd = entity.getYcf_bjzd();
        if (ycf_bjzd != null) {
            stmt.bindString(72, ycf_bjzd);
        }
 
        String ycf_zz = entity.getYcf_zz();
        if (ycf_zz != null) {
            stmt.bindString(73, ycf_zz);
        }
 
        String ycf_yy = entity.getYcf_yy();
        if (ycf_yy != null) {
            stmt.bindString(74, ycf_yy);
        }
 
        String ycf_jg = entity.getYcf_jg();
        if (ycf_jg != null) {
            stmt.bindString(75, ycf_jg);
        }
 
        String ycf_nextdate = entity.getYcf_nextdate();
        if (ycf_nextdate != null) {
            stmt.bindString(76, ycf_nextdate);
        }
 
        String ycf_doctor = entity.getYcf_doctor();
        if (ycf_doctor != null) {
            stmt.bindString(77, ycf_doctor);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(78, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Chanqiansuifangjilu01 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getYcf_id());
        stmt.bindString(3, entity.getNa_id());
 
        String ycf_date = entity.getYcf_date();
        if (ycf_date != null) {
            stmt.bindString(4, ycf_date);
        }
        stmt.bindLong(5, entity.getYcf_week());
        stmt.bindLong(6, entity.getYcf_age());
 
        String ycf_man_name = entity.getYcf_man_name();
        if (ycf_man_name != null) {
            stmt.bindString(7, ycf_man_name);
        }
        stmt.bindLong(8, entity.getYcf_man_age());
 
        String ycf_man_tel = entity.getYcf_man_tel();
        if (ycf_man_tel != null) {
            stmt.bindString(9, ycf_man_tel);
        }
        stmt.bindLong(10, entity.getYcf_number());
        stmt.bindLong(11, entity.getYcf_fm());
        stmt.bindLong(12, entity.getYcf_pfc());
 
        String ycf_mcyj = entity.getYcf_mcyj();
        if (ycf_mcyj != null) {
            stmt.bindString(13, ycf_mcyj);
        }
 
        String ycf_ycq = entity.getYcf_ycq();
        if (ycf_ycq != null) {
            stmt.bindString(14, ycf_ycq);
        }
        stmt.bindLong(15, entity.getYcf_jws());
        stmt.bindLong(16, entity.getYcf_jzs());
        stmt.bindLong(17, entity.getYcf__grs());
        stmt.bindLong(18, entity.getYcf_fkss());
 
        String ycf_fkss_details = entity.getYcf_fkss_details();
        if (ycf_fkss_details != null) {
            stmt.bindString(19, ycf_fkss_details);
        }
 
        String ycf_liuc = entity.getYcf_liuc();
        if (ycf_liuc != null) {
            stmt.bindString(20, ycf_liuc);
        }
 
        String ycf_sit = entity.getYcf_sit();
        if (ycf_sit != null) {
            stmt.bindString(21, ycf_sit);
        }
 
        String ycf_shunc = entity.getYcf_shunc();
        if (ycf_shunc != null) {
            stmt.bindString(22, ycf_shunc);
        }
 
        String ycf_xssw = entity.getYcf_xssw();
        if (ycf_xssw != null) {
            stmt.bindString(23, ycf_xssw);
        }
 
        String ycf_csqx = entity.getYcf_csqx();
        if (ycf_csqx != null) {
            stmt.bindString(24, ycf_csqx);
        }
 
        String hw_id = entity.getHw_id();
        if (hw_id != null) {
            stmt.bindString(25, hw_id);
        }
 
        String bp_id = entity.getBp_id();
        if (bp_id != null) {
            stmt.bindString(26, bp_id);
        }
        stmt.bindLong(27, entity.getYcf_xz());
 
        String ycf_xz_details = entity.getYcf_xz_details();
        if (ycf_xz_details != null) {
            stmt.bindString(28, ycf_xz_details);
        }
        stmt.bindLong(29, entity.getYcf_fei());
 
        String ycf_fei_details = entity.getYcf_fei_details();
        if (ycf_fei_details != null) {
            stmt.bindString(30, ycf_fei_details);
        }
        stmt.bindLong(31, entity.getYcf_wy());
 
        String ycf_wy_details = entity.getYcf_wy_details();
        if (ycf_wy_details != null) {
            stmt.bindString(32, ycf_wy_details);
        }
        stmt.bindLong(33, entity.getYcf_yd());
 
        String ycf_yd_details = entity.getYcf_yd_details();
        if (ycf_yd_details != null) {
            stmt.bindString(34, ycf_yd_details);
        }
        stmt.bindLong(35, entity.getYcf_gj());
 
        String ycf_gj_details = entity.getYcf_gj_details();
        if (ycf_gj_details != null) {
            stmt.bindString(36, ycf_gj_details);
        }
        stmt.bindLong(37, entity.getYcf_zg());
 
        String ycf_zg_details = entity.getYcf_zg_details();
        if (ycf_zg_details != null) {
            stmt.bindString(38, ycf_zg_details);
        }
        stmt.bindLong(39, entity.getYcf_fj());
 
        String ycf_fj_details = entity.getYcf_fj_details();
        if (ycf_fj_details != null) {
            stmt.bindString(40, ycf_fj_details);
        }
 
        String ycf_xhdb = entity.getYcf_xhdb();
        if (ycf_xhdb != null) {
            stmt.bindString(41, ycf_xhdb);
        }
 
        String ycf_bxb = entity.getYcf_bxb();
        if (ycf_bxb != null) {
            stmt.bindString(42, ycf_bxb);
        }
 
        String ycf_xxb = entity.getYcf_xxb();
        if (ycf_xxb != null) {
            stmt.bindString(43, ycf_xxb);
        }
 
        String ycf_xqt = entity.getYcf_xqt();
        if (ycf_xqt != null) {
            stmt.bindString(44, ycf_xqt);
        }
 
        String ycf_ndb = entity.getYcf_ndb();
        if (ycf_ndb != null) {
            stmt.bindString(45, ycf_ndb);
        }
 
        String ycf_ntt = entity.getYcf_ntt();
        if (ycf_ntt != null) {
            stmt.bindString(46, ycf_ntt);
        }
 
        String ycf_nt = entity.getYcf_nt();
        if (ycf_nt != null) {
            stmt.bindString(47, ycf_nt);
        }
 
        String ycf_nqx = entity.getYcf_nqx();
        if (ycf_nqx != null) {
            stmt.bindString(48, ycf_nqx);
        }
 
        String ycf_nqt = entity.getYcf_nqt();
        if (ycf_nqt != null) {
            stmt.bindString(49, ycf_nqt);
        }
 
        String ycf_fz_xx = entity.getYcf_fz_xx();
        if (ycf_fz_xx != null) {
            stmt.bindString(50, ycf_fz_xx);
        }
 
        String ycf_fz_rh = entity.getYcf_fz_rh();
        if (ycf_fz_rh != null) {
            stmt.bindString(51, ycf_fz_rh);
        }
 
        String ycf_fz_xt = entity.getYcf_fz_xt();
        if (ycf_fz_xt != null) {
            stmt.bindString(52, ycf_fz_xt);
        }
        stmt.bindLong(53, entity.getYcf_fz_fmw());
        stmt.bindLong(54, entity.getYcf_fz_qjd());
 
        String ycf_gan_xqgb = entity.getYcf_gan_xqgb();
        if (ycf_gan_xqgb != null) {
            stmt.bindString(55, ycf_gan_xqgb);
        }
 
        String ycf_gan_xqgc = entity.getYcf_gan_xqgc();
        if (ycf_gan_xqgc != null) {
            stmt.bindString(56, ycf_gan_xqgc);
        }
 
        String ycf_gan_bdb = entity.getYcf_gan_bdb();
        if (ycf_gan_bdb != null) {
            stmt.bindString(57, ycf_gan_bdb);
        }
 
        String ycf_gan_zdhs = entity.getYcf_gan_zdhs();
        if (ycf_gan_zdhs != null) {
            stmt.bindString(58, ycf_gan_zdhs);
        }
 
        String ycf_gan_jhdhs = entity.getYcf_gan_jhdhs();
        if (ycf_gan_jhdhs != null) {
            stmt.bindString(59, ycf_gan_jhdhs);
        }
 
        String ycf_shen_xq = entity.getYcf_shen_xq();
        if (ycf_shen_xq != null) {
            stmt.bindString(60, ycf_shen_xq);
        }
 
        String ycf_shen_xn = entity.getYcf_shen_xn();
        if (ycf_shen_xn != null) {
            stmt.bindString(61, ycf_shen_xn);
        }
 
        String ycf_yg_bmky = entity.getYcf_yg_bmky();
        if (ycf_yg_bmky != null) {
            stmt.bindString(62, ycf_yg_bmky);
        }
 
        String ycf_yg_bmkt = entity.getYcf_yg_bmkt();
        if (ycf_yg_bmkt != null) {
            stmt.bindString(63, ycf_yg_bmkt);
        }
 
        String ycf_yg_eky = entity.getYcf_yg_eky();
        if (ycf_yg_eky != null) {
            stmt.bindString(64, ycf_yg_eky);
        }
 
        String ycf_yg_ekt = entity.getYcf_yg_ekt();
        if (ycf_yg_ekt != null) {
            stmt.bindString(65, ycf_yg_ekt);
        }
 
        String ycf_yg_hxkt = entity.getYcf_yg_hxkt();
        if (ycf_yg_hxkt != null) {
            stmt.bindString(66, ycf_yg_hxkt);
        }
        stmt.bindLong(67, entity.getYcf_fz_mdxq());
        stmt.bindLong(68, entity.getYcf_fz_hv());
 
        String ycf_fz_bc = entity.getYcf_fz_bc();
        if (ycf_fz_bc != null) {
            stmt.bindString(69, ycf_fz_bc);
        }
        stmt.bindLong(70, entity.getYcf_ztpg());
 
        String ycf_zt_details = entity.getYcf_zt_details();
        if (ycf_zt_details != null) {
            stmt.bindString(71, ycf_zt_details);
        }
 
        String ycf_bjzd = entity.getYcf_bjzd();
        if (ycf_bjzd != null) {
            stmt.bindString(72, ycf_bjzd);
        }
 
        String ycf_zz = entity.getYcf_zz();
        if (ycf_zz != null) {
            stmt.bindString(73, ycf_zz);
        }
 
        String ycf_yy = entity.getYcf_yy();
        if (ycf_yy != null) {
            stmt.bindString(74, ycf_yy);
        }
 
        String ycf_jg = entity.getYcf_jg();
        if (ycf_jg != null) {
            stmt.bindString(75, ycf_jg);
        }
 
        String ycf_nextdate = entity.getYcf_nextdate();
        if (ycf_nextdate != null) {
            stmt.bindString(76, ycf_nextdate);
        }
 
        String ycf_doctor = entity.getYcf_doctor();
        if (ycf_doctor != null) {
            stmt.bindString(77, ycf_doctor);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(78, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Chanqiansuifangjilu01 readEntity(Cursor cursor, int offset) {
        Chanqiansuifangjilu01 entity = new Chanqiansuifangjilu01( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // ycf_id
            cursor.getString(offset + 2), // na_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ycf_date
            cursor.getInt(offset + 4), // ycf_week
            cursor.getInt(offset + 5), // ycf_age
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ycf_man_name
            cursor.getInt(offset + 7), // ycf_man_age
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ycf_man_tel
            cursor.getInt(offset + 9), // ycf_number
            cursor.getInt(offset + 10), // ycf_fm
            cursor.getInt(offset + 11), // ycf_pfc
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // ycf_mcyj
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // ycf_ycq
            cursor.getInt(offset + 14), // ycf_jws
            cursor.getInt(offset + 15), // ycf_jzs
            cursor.getInt(offset + 16), // ycf__grs
            cursor.getInt(offset + 17), // ycf_fkss
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // ycf_fkss_details
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // ycf_liuc
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // ycf_sit
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // ycf_shunc
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // ycf_xssw
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // ycf_csqx
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // hw_id
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // bp_id
            cursor.getInt(offset + 26), // ycf_xz
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // ycf_xz_details
            cursor.getInt(offset + 28), // ycf_fei
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // ycf_fei_details
            cursor.getInt(offset + 30), // ycf_wy
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // ycf_wy_details
            cursor.getInt(offset + 32), // ycf_yd
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // ycf_yd_details
            cursor.getInt(offset + 34), // ycf_gj
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // ycf_gj_details
            cursor.getInt(offset + 36), // ycf_zg
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // ycf_zg_details
            cursor.getInt(offset + 38), // ycf_fj
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // ycf_fj_details
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // ycf_xhdb
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // ycf_bxb
            cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42), // ycf_xxb
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // ycf_xqt
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // ycf_ndb
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // ycf_ntt
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // ycf_nt
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // ycf_nqx
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // ycf_nqt
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // ycf_fz_xx
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // ycf_fz_rh
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // ycf_fz_xt
            cursor.getInt(offset + 52), // ycf_fz_fmw
            cursor.getInt(offset + 53), // ycf_fz_qjd
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // ycf_gan_xqgb
            cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55), // ycf_gan_xqgc
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // ycf_gan_bdb
            cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57), // ycf_gan_zdhs
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // ycf_gan_jhdhs
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // ycf_shen_xq
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // ycf_shen_xn
            cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61), // ycf_yg_bmky
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // ycf_yg_bmkt
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // ycf_yg_eky
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // ycf_yg_ekt
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // ycf_yg_hxkt
            cursor.getInt(offset + 66), // ycf_fz_mdxq
            cursor.getInt(offset + 67), // ycf_fz_hv
            cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68), // ycf_fz_bc
            cursor.getInt(offset + 69), // ycf_ztpg
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70), // ycf_zt_details
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71), // ycf_bjzd
            cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72), // ycf_zz
            cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73), // ycf_yy
            cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74), // ycf_jg
            cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75), // ycf_nextdate
            cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76), // ycf_doctor
            cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Chanqiansuifangjilu01 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setYcf_id(cursor.getString(offset + 1));
        entity.setNa_id(cursor.getString(offset + 2));
        entity.setYcf_date(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setYcf_week(cursor.getInt(offset + 4));
        entity.setYcf_age(cursor.getInt(offset + 5));
        entity.setYcf_man_name(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setYcf_man_age(cursor.getInt(offset + 7));
        entity.setYcf_man_tel(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setYcf_number(cursor.getInt(offset + 9));
        entity.setYcf_fm(cursor.getInt(offset + 10));
        entity.setYcf_pfc(cursor.getInt(offset + 11));
        entity.setYcf_mcyj(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setYcf_ycq(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setYcf_jws(cursor.getInt(offset + 14));
        entity.setYcf_jzs(cursor.getInt(offset + 15));
        entity.setYcf__grs(cursor.getInt(offset + 16));
        entity.setYcf_fkss(cursor.getInt(offset + 17));
        entity.setYcf_fkss_details(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setYcf_liuc(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setYcf_sit(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setYcf_shunc(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setYcf_xssw(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setYcf_csqx(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setHw_id(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setBp_id(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setYcf_xz(cursor.getInt(offset + 26));
        entity.setYcf_xz_details(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setYcf_fei(cursor.getInt(offset + 28));
        entity.setYcf_fei_details(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setYcf_wy(cursor.getInt(offset + 30));
        entity.setYcf_wy_details(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setYcf_yd(cursor.getInt(offset + 32));
        entity.setYcf_yd_details(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setYcf_gj(cursor.getInt(offset + 34));
        entity.setYcf_gj_details(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setYcf_zg(cursor.getInt(offset + 36));
        entity.setYcf_zg_details(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setYcf_fj(cursor.getInt(offset + 38));
        entity.setYcf_fj_details(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setYcf_xhdb(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setYcf_bxb(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setYcf_xxb(cursor.isNull(offset + 42) ? null : cursor.getString(offset + 42));
        entity.setYcf_xqt(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setYcf_ndb(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setYcf_ntt(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setYcf_nt(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setYcf_nqx(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setYcf_nqt(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setYcf_fz_xx(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setYcf_fz_rh(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setYcf_fz_xt(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setYcf_fz_fmw(cursor.getInt(offset + 52));
        entity.setYcf_fz_qjd(cursor.getInt(offset + 53));
        entity.setYcf_gan_xqgb(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setYcf_gan_xqgc(cursor.isNull(offset + 55) ? null : cursor.getString(offset + 55));
        entity.setYcf_gan_bdb(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setYcf_gan_zdhs(cursor.isNull(offset + 57) ? null : cursor.getString(offset + 57));
        entity.setYcf_gan_jhdhs(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setYcf_shen_xq(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setYcf_shen_xn(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setYcf_yg_bmky(cursor.isNull(offset + 61) ? null : cursor.getString(offset + 61));
        entity.setYcf_yg_bmkt(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setYcf_yg_eky(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setYcf_yg_ekt(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setYcf_yg_hxkt(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setYcf_fz_mdxq(cursor.getInt(offset + 66));
        entity.setYcf_fz_hv(cursor.getInt(offset + 67));
        entity.setYcf_fz_bc(cursor.isNull(offset + 68) ? null : cursor.getString(offset + 68));
        entity.setYcf_ztpg(cursor.getInt(offset + 69));
        entity.setYcf_zt_details(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setYcf_bjzd(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
        entity.setYcf_zz(cursor.isNull(offset + 72) ? null : cursor.getString(offset + 72));
        entity.setYcf_yy(cursor.isNull(offset + 73) ? null : cursor.getString(offset + 73));
        entity.setYcf_jg(cursor.isNull(offset + 74) ? null : cursor.getString(offset + 74));
        entity.setYcf_nextdate(cursor.isNull(offset + 75) ? null : cursor.getString(offset + 75));
        entity.setYcf_doctor(cursor.isNull(offset + 76) ? null : cursor.getString(offset + 76));
        entity.setCreateDate(cursor.isNull(offset + 77) ? null : cursor.getString(offset + 77));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Chanqiansuifangjilu01 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Chanqiansuifangjilu01 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Chanqiansuifangjilu01 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
