package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.JianKangTiJianBiao_B;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JIAN_KANG_TI_JIAN_BIAO__B".
*/
public class JianKangTiJianBiao_BDao extends AbstractDao<JianKangTiJianBiao_B, Long> {

    public static final String TABLENAME = "JIAN_KANG_TI_JIAN_BIAO__B";

    /**
     * Properties of entity JianKangTiJianBiao_B.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Jktj1_id = new Property(1, String.class, "jktj1_id", false, "JKTJ1_ID");
        public final static Property Jktj_id = new Property(2, String.class, "jktj_id", false, "JKTJ_ID");
        public final static Property Jktj1_kouc = new Property(3, int.class, "jktj1_kouc", false, "JKTJ1_KOUC");
        public final static Property Jktj1_chil = new Property(4, int.class, "jktj1_chil", false, "JKTJ1_CHIL");
        public final static Property Jktj1_quec = new Property(5, String.class, "jktj1_quec", false, "JKTJ1_QUEC");
        public final static Property Jktj1_quc = new Property(6, String.class, "jktj1_quc", false, "JKTJ1_QUC");
        public final static Property Jktj1_yic = new Property(7, String.class, "jktj1_yic", false, "JKTJ1_YIC");
        public final static Property Jktj1_yanb = new Property(8, int.class, "jktj1_yanb", false, "JKTJ1_YANB");
        public final static Property Jktj1_slz = new Property(9, String.class, "jktj1_slz", false, "JKTJ1_SLZ");
        public final static Property Jktj1_sly = new Property(10, String.class, "jktj1_sly", false, "JKTJ1_SLY");
        public final static Property Jktj1_jzslz = new Property(11, String.class, "jktj1_jzslz", false, "JKTJ1_JZSLZ");
        public final static Property Jktj1_jzsly = new Property(12, String.class, "jktj1_jzsly", false, "JKTJ1_JZSLY");
        public final static Property Jktj1_tingl = new Property(13, int.class, "jktj1_tingl", false, "JKTJ1_TINGL");
        public final static Property Jktj1_ydgn = new Property(14, int.class, "jktj1_ydgn", false, "JKTJ1_YDGN");
        public final static Property Jktj1_yd = new Property(15, int.class, "jktj1_yd", false, "JKTJ1_YD");
        public final static Property Jktj1_yd_ms = new Property(16, String.class, "jktj1_yd_ms", false, "JKTJ1_YD_MS");
        public final static Property Jktj1_pif = new Property(17, int.class, "jktj1_pif", false, "JKTJ1_PIF");
        public final static Property Jktj1_gongm = new Property(18, int.class, "jktj1_gongm", false, "JKTJ1_GONGM");
        public final static Property Jktj1_linbj = new Property(19, int.class, "jktj1_linbj", false, "JKTJ1_LINBJ");
        public final static Property Jktj1_tongzx = new Property(20, int.class, "jktj1_tongzx", false, "JKTJ1_TONGZX");
        public final static Property Jktj1_huxy = new Property(21, int.class, "jktj1_huxy", false, "JKTJ1_HUXY");
        public final static Property Jktj1_huxy_ms = new Property(22, String.class, "jktj1_huxy_ms", false, "JKTJ1_HUXY_MS");
        public final static Property Jktj1_luoy = new Property(23, int.class, "jktj1_luoy", false, "JKTJ1_LUOY");
        public final static Property Jktj1_xinl = new Property(24, String.class, "jktj1_xinl", false, "JKTJ1_XINL");
        public final static Property Jktj1_xinlv = new Property(25, int.class, "jktj1_xinlv", false, "JKTJ1_XINLV");
        public final static Property Jktj1_zay = new Property(26, int.class, "jktj1_zay", false, "JKTJ1_ZAY");
        public final static Property Jktj1_zay_ms = new Property(27, String.class, "jktj1_zay_ms", false, "JKTJ1_ZAY_MS");
        public final static Property Jktj1_yat = new Property(28, int.class, "jktj1_yat", false, "JKTJ1_YAT");
        public final static Property Jktj1_yat_ms = new Property(29, String.class, "jktj1_yat_ms", false, "JKTJ1_YAT_MS");
        public final static Property Jktj1_baok = new Property(30, int.class, "jktj1_baok", false, "JKTJ1_BAOK");
        public final static Property Jktj1_baok_ms = new Property(31, String.class, "jktj1_baok_ms", false, "JKTJ1_BAOK_MS");
        public final static Property Jktj1_gand = new Property(32, int.class, "jktj1_gand", false, "JKTJ1_GAND");
        public final static Property Jktj1_gand_ms = new Property(33, String.class, "jktj1_gand_ms", false, "JKTJ1_GAND_MS");
        public final static Property Jktj1_pid = new Property(34, int.class, "jktj1_pid", false, "JKTJ1_PID");
        public final static Property Jktj1_pid_ms = new Property(35, String.class, "jktj1_pid_ms", false, "JKTJ1_PID_MS");
        public final static Property Jktj1_zhuoy = new Property(36, int.class, "jktj1_zhuoy", false, "JKTJ1_ZHUOY");
        public final static Property Jktj1_zhuoy_ms = new Property(37, String.class, "jktj1_zhuoy_ms", false, "JKTJ1_ZHUOY_MS");
        public final static Property Jktj1_xzsz = new Property(38, int.class, "jktj1_xzsz", false, "JKTJ1_XZSZ");
        public final static Property Jktj1_zbdmbd = new Property(39, int.class, "jktj1_zbdmbd", false, "JKTJ1_ZBDMBD");
        public final static Property Jktj1_gmzz = new Property(40, int.class, "jktj1_gmzz", false, "JKTJ1_GMZZ");
        public final static Property Jktj1_rux = new Property(41, int.class, "jktj1_rux", false, "JKTJ1_RUX");
        public final static Property Jktj1_waiy = new Property(42, int.class, "jktj1_waiy", false, "JKTJ1_WAIY");
        public final static Property Jktj1_waiy_ms = new Property(43, String.class, "jktj1_waiy_ms", false, "JKTJ1_WAIY_MS");
        public final static Property Jktj1_yind = new Property(44, int.class, "jktj1_yind", false, "JKTJ1_YIND");
        public final static Property Jktj1_yind_ms = new Property(45, String.class, "jktj1_yind_ms", false, "JKTJ1_YIND_MS");
        public final static Property Jktj1_gongj = new Property(46, int.class, "jktj1_gongj", false, "JKTJ1_GONGJ");
        public final static Property Jktj1_gongj_ms = new Property(47, String.class, "jktj1_gongj_ms", false, "JKTJ1_GONGJ_MS");
        public final static Property Jktj1_gongt = new Property(48, int.class, "jktj1_gongt", false, "JKTJ1_GONGT");
        public final static Property Jktj1_gongt_ms = new Property(49, String.class, "jktj1_gongt_ms", false, "JKTJ1_GONGT_MS");
        public final static Property Jktj1_fuj = new Property(50, int.class, "jktj1_fuj", false, "JKTJ1_FUJ");
        public final static Property Jktj1_fuj_ms = new Property(51, String.class, "jktj1_fuj_ms", false, "JKTJ1_FUJ_MS");
        public final static Property Jktj1_bz = new Property(52, String.class, "jktj1_bz", false, "JKTJ1_BZ");
        public final static Property CreateDate = new Property(53, String.class, "createDate", false, "CREATE_DATE");
    }


    public JianKangTiJianBiao_BDao(DaoConfig config) {
        super(config);
    }
    
    public JianKangTiJianBiao_BDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JIAN_KANG_TI_JIAN_BIAO__B\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JKTJ1_ID\" TEXT NOT NULL ," + // 1: jktj1_id
                "\"JKTJ_ID\" TEXT NOT NULL ," + // 2: jktj_id
                "\"JKTJ1_KOUC\" INTEGER NOT NULL ," + // 3: jktj1_kouc
                "\"JKTJ1_CHIL\" INTEGER NOT NULL ," + // 4: jktj1_chil
                "\"JKTJ1_QUEC\" TEXT," + // 5: jktj1_quec
                "\"JKTJ1_QUC\" TEXT," + // 6: jktj1_quc
                "\"JKTJ1_YIC\" TEXT," + // 7: jktj1_yic
                "\"JKTJ1_YANB\" INTEGER NOT NULL ," + // 8: jktj1_yanb
                "\"JKTJ1_SLZ\" TEXT," + // 9: jktj1_slz
                "\"JKTJ1_SLY\" TEXT," + // 10: jktj1_sly
                "\"JKTJ1_JZSLZ\" TEXT," + // 11: jktj1_jzslz
                "\"JKTJ1_JZSLY\" TEXT," + // 12: jktj1_jzsly
                "\"JKTJ1_TINGL\" INTEGER NOT NULL ," + // 13: jktj1_tingl
                "\"JKTJ1_YDGN\" INTEGER NOT NULL ," + // 14: jktj1_ydgn
                "\"JKTJ1_YD\" INTEGER NOT NULL ," + // 15: jktj1_yd
                "\"JKTJ1_YD_MS\" TEXT," + // 16: jktj1_yd_ms
                "\"JKTJ1_PIF\" INTEGER NOT NULL ," + // 17: jktj1_pif
                "\"JKTJ1_GONGM\" INTEGER NOT NULL ," + // 18: jktj1_gongm
                "\"JKTJ1_LINBJ\" INTEGER NOT NULL ," + // 19: jktj1_linbj
                "\"JKTJ1_TONGZX\" INTEGER NOT NULL ," + // 20: jktj1_tongzx
                "\"JKTJ1_HUXY\" INTEGER NOT NULL ," + // 21: jktj1_huxy
                "\"JKTJ1_HUXY_MS\" TEXT," + // 22: jktj1_huxy_ms
                "\"JKTJ1_LUOY\" INTEGER NOT NULL ," + // 23: jktj1_luoy
                "\"JKTJ1_XINL\" TEXT," + // 24: jktj1_xinl
                "\"JKTJ1_XINLV\" INTEGER NOT NULL ," + // 25: jktj1_xinlv
                "\"JKTJ1_ZAY\" INTEGER NOT NULL ," + // 26: jktj1_zay
                "\"JKTJ1_ZAY_MS\" TEXT," + // 27: jktj1_zay_ms
                "\"JKTJ1_YAT\" INTEGER NOT NULL ," + // 28: jktj1_yat
                "\"JKTJ1_YAT_MS\" TEXT," + // 29: jktj1_yat_ms
                "\"JKTJ1_BAOK\" INTEGER NOT NULL ," + // 30: jktj1_baok
                "\"JKTJ1_BAOK_MS\" TEXT," + // 31: jktj1_baok_ms
                "\"JKTJ1_GAND\" INTEGER NOT NULL ," + // 32: jktj1_gand
                "\"JKTJ1_GAND_MS\" TEXT," + // 33: jktj1_gand_ms
                "\"JKTJ1_PID\" INTEGER NOT NULL ," + // 34: jktj1_pid
                "\"JKTJ1_PID_MS\" TEXT," + // 35: jktj1_pid_ms
                "\"JKTJ1_ZHUOY\" INTEGER NOT NULL ," + // 36: jktj1_zhuoy
                "\"JKTJ1_ZHUOY_MS\" TEXT," + // 37: jktj1_zhuoy_ms
                "\"JKTJ1_XZSZ\" INTEGER NOT NULL ," + // 38: jktj1_xzsz
                "\"JKTJ1_ZBDMBD\" INTEGER NOT NULL ," + // 39: jktj1_zbdmbd
                "\"JKTJ1_GMZZ\" INTEGER NOT NULL ," + // 40: jktj1_gmzz
                "\"JKTJ1_RUX\" INTEGER NOT NULL ," + // 41: jktj1_rux
                "\"JKTJ1_WAIY\" INTEGER NOT NULL ," + // 42: jktj1_waiy
                "\"JKTJ1_WAIY_MS\" TEXT," + // 43: jktj1_waiy_ms
                "\"JKTJ1_YIND\" INTEGER NOT NULL ," + // 44: jktj1_yind
                "\"JKTJ1_YIND_MS\" TEXT," + // 45: jktj1_yind_ms
                "\"JKTJ1_GONGJ\" INTEGER NOT NULL ," + // 46: jktj1_gongj
                "\"JKTJ1_GONGJ_MS\" TEXT," + // 47: jktj1_gongj_ms
                "\"JKTJ1_GONGT\" INTEGER NOT NULL ," + // 48: jktj1_gongt
                "\"JKTJ1_GONGT_MS\" TEXT," + // 49: jktj1_gongt_ms
                "\"JKTJ1_FUJ\" INTEGER NOT NULL ," + // 50: jktj1_fuj
                "\"JKTJ1_FUJ_MS\" TEXT," + // 51: jktj1_fuj_ms
                "\"JKTJ1_BZ\" TEXT," + // 52: jktj1_bz
                "\"CREATE_DATE\" TEXT);"); // 53: createDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JIAN_KANG_TI_JIAN_BIAO__B\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JianKangTiJianBiao_B entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJktj1_id());
        stmt.bindString(3, entity.getJktj_id());
        stmt.bindLong(4, entity.getJktj1_kouc());
        stmt.bindLong(5, entity.getJktj1_chil());
 
        String jktj1_quec = entity.getJktj1_quec();
        if (jktj1_quec != null) {
            stmt.bindString(6, jktj1_quec);
        }
 
        String jktj1_quc = entity.getJktj1_quc();
        if (jktj1_quc != null) {
            stmt.bindString(7, jktj1_quc);
        }
 
        String jktj1_yic = entity.getJktj1_yic();
        if (jktj1_yic != null) {
            stmt.bindString(8, jktj1_yic);
        }
        stmt.bindLong(9, entity.getJktj1_yanb());
 
        String jktj1_slz = entity.getJktj1_slz();
        if (jktj1_slz != null) {
            stmt.bindString(10, jktj1_slz);
        }
 
        String jktj1_sly = entity.getJktj1_sly();
        if (jktj1_sly != null) {
            stmt.bindString(11, jktj1_sly);
        }
 
        String jktj1_jzslz = entity.getJktj1_jzslz();
        if (jktj1_jzslz != null) {
            stmt.bindString(12, jktj1_jzslz);
        }
 
        String jktj1_jzsly = entity.getJktj1_jzsly();
        if (jktj1_jzsly != null) {
            stmt.bindString(13, jktj1_jzsly);
        }
        stmt.bindLong(14, entity.getJktj1_tingl());
        stmt.bindLong(15, entity.getJktj1_ydgn());
        stmt.bindLong(16, entity.getJktj1_yd());
 
        String jktj1_yd_ms = entity.getJktj1_yd_ms();
        if (jktj1_yd_ms != null) {
            stmt.bindString(17, jktj1_yd_ms);
        }
        stmt.bindLong(18, entity.getJktj1_pif());
        stmt.bindLong(19, entity.getJktj1_gongm());
        stmt.bindLong(20, entity.getJktj1_linbj());
        stmt.bindLong(21, entity.getJktj1_tongzx());
        stmt.bindLong(22, entity.getJktj1_huxy());
 
        String jktj1_huxy_ms = entity.getJktj1_huxy_ms();
        if (jktj1_huxy_ms != null) {
            stmt.bindString(23, jktj1_huxy_ms);
        }
        stmt.bindLong(24, entity.getJktj1_luoy());
 
        String jktj1_xinl = entity.getJktj1_xinl();
        if (jktj1_xinl != null) {
            stmt.bindString(25, jktj1_xinl);
        }
        stmt.bindLong(26, entity.getJktj1_xinlv());
        stmt.bindLong(27, entity.getJktj1_zay());
 
        String jktj1_zay_ms = entity.getJktj1_zay_ms();
        if (jktj1_zay_ms != null) {
            stmt.bindString(28, jktj1_zay_ms);
        }
        stmt.bindLong(29, entity.getJktj1_yat());
 
        String jktj1_yat_ms = entity.getJktj1_yat_ms();
        if (jktj1_yat_ms != null) {
            stmt.bindString(30, jktj1_yat_ms);
        }
        stmt.bindLong(31, entity.getJktj1_baok());
 
        String jktj1_baok_ms = entity.getJktj1_baok_ms();
        if (jktj1_baok_ms != null) {
            stmt.bindString(32, jktj1_baok_ms);
        }
        stmt.bindLong(33, entity.getJktj1_gand());
 
        String jktj1_gand_ms = entity.getJktj1_gand_ms();
        if (jktj1_gand_ms != null) {
            stmt.bindString(34, jktj1_gand_ms);
        }
        stmt.bindLong(35, entity.getJktj1_pid());
 
        String jktj1_pid_ms = entity.getJktj1_pid_ms();
        if (jktj1_pid_ms != null) {
            stmt.bindString(36, jktj1_pid_ms);
        }
        stmt.bindLong(37, entity.getJktj1_zhuoy());
 
        String jktj1_zhuoy_ms = entity.getJktj1_zhuoy_ms();
        if (jktj1_zhuoy_ms != null) {
            stmt.bindString(38, jktj1_zhuoy_ms);
        }
        stmt.bindLong(39, entity.getJktj1_xzsz());
        stmt.bindLong(40, entity.getJktj1_zbdmbd());
        stmt.bindLong(41, entity.getJktj1_gmzz());
        stmt.bindLong(42, entity.getJktj1_rux());
        stmt.bindLong(43, entity.getJktj1_waiy());
 
        String jktj1_waiy_ms = entity.getJktj1_waiy_ms();
        if (jktj1_waiy_ms != null) {
            stmt.bindString(44, jktj1_waiy_ms);
        }
        stmt.bindLong(45, entity.getJktj1_yind());
 
        String jktj1_yind_ms = entity.getJktj1_yind_ms();
        if (jktj1_yind_ms != null) {
            stmt.bindString(46, jktj1_yind_ms);
        }
        stmt.bindLong(47, entity.getJktj1_gongj());
 
        String jktj1_gongj_ms = entity.getJktj1_gongj_ms();
        if (jktj1_gongj_ms != null) {
            stmt.bindString(48, jktj1_gongj_ms);
        }
        stmt.bindLong(49, entity.getJktj1_gongt());
 
        String jktj1_gongt_ms = entity.getJktj1_gongt_ms();
        if (jktj1_gongt_ms != null) {
            stmt.bindString(50, jktj1_gongt_ms);
        }
        stmt.bindLong(51, entity.getJktj1_fuj());
 
        String jktj1_fuj_ms = entity.getJktj1_fuj_ms();
        if (jktj1_fuj_ms != null) {
            stmt.bindString(52, jktj1_fuj_ms);
        }
 
        String jktj1_bz = entity.getJktj1_bz();
        if (jktj1_bz != null) {
            stmt.bindString(53, jktj1_bz);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(54, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JianKangTiJianBiao_B entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJktj1_id());
        stmt.bindString(3, entity.getJktj_id());
        stmt.bindLong(4, entity.getJktj1_kouc());
        stmt.bindLong(5, entity.getJktj1_chil());
 
        String jktj1_quec = entity.getJktj1_quec();
        if (jktj1_quec != null) {
            stmt.bindString(6, jktj1_quec);
        }
 
        String jktj1_quc = entity.getJktj1_quc();
        if (jktj1_quc != null) {
            stmt.bindString(7, jktj1_quc);
        }
 
        String jktj1_yic = entity.getJktj1_yic();
        if (jktj1_yic != null) {
            stmt.bindString(8, jktj1_yic);
        }
        stmt.bindLong(9, entity.getJktj1_yanb());
 
        String jktj1_slz = entity.getJktj1_slz();
        if (jktj1_slz != null) {
            stmt.bindString(10, jktj1_slz);
        }
 
        String jktj1_sly = entity.getJktj1_sly();
        if (jktj1_sly != null) {
            stmt.bindString(11, jktj1_sly);
        }
 
        String jktj1_jzslz = entity.getJktj1_jzslz();
        if (jktj1_jzslz != null) {
            stmt.bindString(12, jktj1_jzslz);
        }
 
        String jktj1_jzsly = entity.getJktj1_jzsly();
        if (jktj1_jzsly != null) {
            stmt.bindString(13, jktj1_jzsly);
        }
        stmt.bindLong(14, entity.getJktj1_tingl());
        stmt.bindLong(15, entity.getJktj1_ydgn());
        stmt.bindLong(16, entity.getJktj1_yd());
 
        String jktj1_yd_ms = entity.getJktj1_yd_ms();
        if (jktj1_yd_ms != null) {
            stmt.bindString(17, jktj1_yd_ms);
        }
        stmt.bindLong(18, entity.getJktj1_pif());
        stmt.bindLong(19, entity.getJktj1_gongm());
        stmt.bindLong(20, entity.getJktj1_linbj());
        stmt.bindLong(21, entity.getJktj1_tongzx());
        stmt.bindLong(22, entity.getJktj1_huxy());
 
        String jktj1_huxy_ms = entity.getJktj1_huxy_ms();
        if (jktj1_huxy_ms != null) {
            stmt.bindString(23, jktj1_huxy_ms);
        }
        stmt.bindLong(24, entity.getJktj1_luoy());
 
        String jktj1_xinl = entity.getJktj1_xinl();
        if (jktj1_xinl != null) {
            stmt.bindString(25, jktj1_xinl);
        }
        stmt.bindLong(26, entity.getJktj1_xinlv());
        stmt.bindLong(27, entity.getJktj1_zay());
 
        String jktj1_zay_ms = entity.getJktj1_zay_ms();
        if (jktj1_zay_ms != null) {
            stmt.bindString(28, jktj1_zay_ms);
        }
        stmt.bindLong(29, entity.getJktj1_yat());
 
        String jktj1_yat_ms = entity.getJktj1_yat_ms();
        if (jktj1_yat_ms != null) {
            stmt.bindString(30, jktj1_yat_ms);
        }
        stmt.bindLong(31, entity.getJktj1_baok());
 
        String jktj1_baok_ms = entity.getJktj1_baok_ms();
        if (jktj1_baok_ms != null) {
            stmt.bindString(32, jktj1_baok_ms);
        }
        stmt.bindLong(33, entity.getJktj1_gand());
 
        String jktj1_gand_ms = entity.getJktj1_gand_ms();
        if (jktj1_gand_ms != null) {
            stmt.bindString(34, jktj1_gand_ms);
        }
        stmt.bindLong(35, entity.getJktj1_pid());
 
        String jktj1_pid_ms = entity.getJktj1_pid_ms();
        if (jktj1_pid_ms != null) {
            stmt.bindString(36, jktj1_pid_ms);
        }
        stmt.bindLong(37, entity.getJktj1_zhuoy());
 
        String jktj1_zhuoy_ms = entity.getJktj1_zhuoy_ms();
        if (jktj1_zhuoy_ms != null) {
            stmt.bindString(38, jktj1_zhuoy_ms);
        }
        stmt.bindLong(39, entity.getJktj1_xzsz());
        stmt.bindLong(40, entity.getJktj1_zbdmbd());
        stmt.bindLong(41, entity.getJktj1_gmzz());
        stmt.bindLong(42, entity.getJktj1_rux());
        stmt.bindLong(43, entity.getJktj1_waiy());
 
        String jktj1_waiy_ms = entity.getJktj1_waiy_ms();
        if (jktj1_waiy_ms != null) {
            stmt.bindString(44, jktj1_waiy_ms);
        }
        stmt.bindLong(45, entity.getJktj1_yind());
 
        String jktj1_yind_ms = entity.getJktj1_yind_ms();
        if (jktj1_yind_ms != null) {
            stmt.bindString(46, jktj1_yind_ms);
        }
        stmt.bindLong(47, entity.getJktj1_gongj());
 
        String jktj1_gongj_ms = entity.getJktj1_gongj_ms();
        if (jktj1_gongj_ms != null) {
            stmt.bindString(48, jktj1_gongj_ms);
        }
        stmt.bindLong(49, entity.getJktj1_gongt());
 
        String jktj1_gongt_ms = entity.getJktj1_gongt_ms();
        if (jktj1_gongt_ms != null) {
            stmt.bindString(50, jktj1_gongt_ms);
        }
        stmt.bindLong(51, entity.getJktj1_fuj());
 
        String jktj1_fuj_ms = entity.getJktj1_fuj_ms();
        if (jktj1_fuj_ms != null) {
            stmt.bindString(52, jktj1_fuj_ms);
        }
 
        String jktj1_bz = entity.getJktj1_bz();
        if (jktj1_bz != null) {
            stmt.bindString(53, jktj1_bz);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(54, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JianKangTiJianBiao_B readEntity(Cursor cursor, int offset) {
        JianKangTiJianBiao_B entity = new JianKangTiJianBiao_B( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // jktj1_id
            cursor.getString(offset + 2), // jktj_id
            cursor.getInt(offset + 3), // jktj1_kouc
            cursor.getInt(offset + 4), // jktj1_chil
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jktj1_quec
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // jktj1_quc
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // jktj1_yic
            cursor.getInt(offset + 8), // jktj1_yanb
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // jktj1_slz
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // jktj1_sly
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // jktj1_jzslz
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // jktj1_jzsly
            cursor.getInt(offset + 13), // jktj1_tingl
            cursor.getInt(offset + 14), // jktj1_ydgn
            cursor.getInt(offset + 15), // jktj1_yd
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // jktj1_yd_ms
            cursor.getInt(offset + 17), // jktj1_pif
            cursor.getInt(offset + 18), // jktj1_gongm
            cursor.getInt(offset + 19), // jktj1_linbj
            cursor.getInt(offset + 20), // jktj1_tongzx
            cursor.getInt(offset + 21), // jktj1_huxy
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // jktj1_huxy_ms
            cursor.getInt(offset + 23), // jktj1_luoy
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // jktj1_xinl
            cursor.getInt(offset + 25), // jktj1_xinlv
            cursor.getInt(offset + 26), // jktj1_zay
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // jktj1_zay_ms
            cursor.getInt(offset + 28), // jktj1_yat
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // jktj1_yat_ms
            cursor.getInt(offset + 30), // jktj1_baok
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // jktj1_baok_ms
            cursor.getInt(offset + 32), // jktj1_gand
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // jktj1_gand_ms
            cursor.getInt(offset + 34), // jktj1_pid
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // jktj1_pid_ms
            cursor.getInt(offset + 36), // jktj1_zhuoy
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // jktj1_zhuoy_ms
            cursor.getInt(offset + 38), // jktj1_xzsz
            cursor.getInt(offset + 39), // jktj1_zbdmbd
            cursor.getInt(offset + 40), // jktj1_gmzz
            cursor.getInt(offset + 41), // jktj1_rux
            cursor.getInt(offset + 42), // jktj1_waiy
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // jktj1_waiy_ms
            cursor.getInt(offset + 44), // jktj1_yind
            cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45), // jktj1_yind_ms
            cursor.getInt(offset + 46), // jktj1_gongj
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // jktj1_gongj_ms
            cursor.getInt(offset + 48), // jktj1_gongt
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // jktj1_gongt_ms
            cursor.getInt(offset + 50), // jktj1_fuj
            cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51), // jktj1_fuj_ms
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // jktj1_bz
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JianKangTiJianBiao_B entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJktj1_id(cursor.getString(offset + 1));
        entity.setJktj_id(cursor.getString(offset + 2));
        entity.setJktj1_kouc(cursor.getInt(offset + 3));
        entity.setJktj1_chil(cursor.getInt(offset + 4));
        entity.setJktj1_quec(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setJktj1_quc(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJktj1_yic(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setJktj1_yanb(cursor.getInt(offset + 8));
        entity.setJktj1_slz(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setJktj1_sly(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setJktj1_jzslz(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setJktj1_jzsly(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setJktj1_tingl(cursor.getInt(offset + 13));
        entity.setJktj1_ydgn(cursor.getInt(offset + 14));
        entity.setJktj1_yd(cursor.getInt(offset + 15));
        entity.setJktj1_yd_ms(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setJktj1_pif(cursor.getInt(offset + 17));
        entity.setJktj1_gongm(cursor.getInt(offset + 18));
        entity.setJktj1_linbj(cursor.getInt(offset + 19));
        entity.setJktj1_tongzx(cursor.getInt(offset + 20));
        entity.setJktj1_huxy(cursor.getInt(offset + 21));
        entity.setJktj1_huxy_ms(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setJktj1_luoy(cursor.getInt(offset + 23));
        entity.setJktj1_xinl(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setJktj1_xinlv(cursor.getInt(offset + 25));
        entity.setJktj1_zay(cursor.getInt(offset + 26));
        entity.setJktj1_zay_ms(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setJktj1_yat(cursor.getInt(offset + 28));
        entity.setJktj1_yat_ms(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setJktj1_baok(cursor.getInt(offset + 30));
        entity.setJktj1_baok_ms(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setJktj1_gand(cursor.getInt(offset + 32));
        entity.setJktj1_gand_ms(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setJktj1_pid(cursor.getInt(offset + 34));
        entity.setJktj1_pid_ms(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setJktj1_zhuoy(cursor.getInt(offset + 36));
        entity.setJktj1_zhuoy_ms(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setJktj1_xzsz(cursor.getInt(offset + 38));
        entity.setJktj1_zbdmbd(cursor.getInt(offset + 39));
        entity.setJktj1_gmzz(cursor.getInt(offset + 40));
        entity.setJktj1_rux(cursor.getInt(offset + 41));
        entity.setJktj1_waiy(cursor.getInt(offset + 42));
        entity.setJktj1_waiy_ms(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setJktj1_yind(cursor.getInt(offset + 44));
        entity.setJktj1_yind_ms(cursor.isNull(offset + 45) ? null : cursor.getString(offset + 45));
        entity.setJktj1_gongj(cursor.getInt(offset + 46));
        entity.setJktj1_gongj_ms(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setJktj1_gongt(cursor.getInt(offset + 48));
        entity.setJktj1_gongt_ms(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setJktj1_fuj(cursor.getInt(offset + 50));
        entity.setJktj1_fuj_ms(cursor.isNull(offset + 51) ? null : cursor.getString(offset + 51));
        entity.setJktj1_bz(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setCreateDate(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JianKangTiJianBiao_B entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JianKangTiJianBiao_B entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JianKangTiJianBiao_B entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
