package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.JianKangTiJianBiao_A;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JIAN_KANG_TI_JIAN_BIAO__A".
*/
public class JianKangTiJianBiao_ADao extends AbstractDao<JianKangTiJianBiao_A, Long> {

    public static final String TABLENAME = "JIAN_KANG_TI_JIAN_BIAO__A";

    /**
     * Properties of entity JianKangTiJianBiao_A.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Jktj_id = new Property(1, String.class, "jktj_id", false, "JKTJ_ID");
        public final static Property Na_id = new Property(2, String.class, "na_id", false, "NA_ID");
        public final static Property Jktj_date = new Property(3, String.class, "jktj_date", false, "JKTJ_DATE");
        public final static Property Jktj_doctor = new Property(4, String.class, "jktj_doctor", false, "JKTJ_DOCTOR");
        public final static Property Symptom_id = new Property(5, int.class, "symptom_id", false, "SYMPTOM_ID");
        public final static Property Jktj_tw = new Property(6, String.class, "jktj_tw", false, "JKTJ_TW");
        public final static Property Jktj_ml = new Property(7, String.class, "jktj_ml", false, "JKTJ_ML");
        public final static Property Jktj_hxpl = new Property(8, String.class, "jktj_hxpl", false, "JKTJ_HXPL");
        public final static Property Zbp_id = new Property(9, String.class, "zbp_id", false, "ZBP_ID");
        public final static Property Ybp_id = new Property(10, String.class, "ybp_id", false, "YBP_ID");
        public final static Property Hw_id = new Property(11, String.class, "hw_id", false, "HW_ID");
        public final static Property Jktj_yaow = new Property(12, String.class, "jktj_yaow", false, "JKTJ_YAOW");
        public final static Property Jktj_lnrjk = new Property(13, int.class, "jktj_lnrjk", false, "JKTJ_LNRJK");
        public final static Property Jktj_lnrzl = new Property(14, int.class, "jktj_lnrzl", false, "JKTJ_LNRZL");
        public final static Property Jktj_lnrrz = new Property(15, int.class, "jktj_lnrrz", false, "JKTJ_LNRRZ");
        public final static Property Jktj_zlzt = new Property(16, String.class, "jktj_zlzt", false, "JKTJ_ZLZT");
        public final static Property Jktj_lnrqg = new Property(17, int.class, "jktj_lnrqg", false, "JKTJ_LNRQG");
        public final static Property Jktj_lnryy = new Property(18, String.class, "jktj_lnryy", false, "JKTJ_LNRYY");
        public final static Property Jktj_dlpl = new Property(19, int.class, "jktj_dlpl", false, "JKTJ_DLPL");
        public final static Property Jktj_dlsj = new Property(20, String.class, "jktj_dlsj", false, "JKTJ_DLSJ");
        public final static Property Jktj_jcsj = new Property(21, String.class, "jktj_jcsj", false, "JKTJ_JCSJ");
        public final static Property Jktj_dlfs = new Property(22, String.class, "jktj_dlfs", false, "JKTJ_DLFS");
        public final static Property Jktj_ysxg = new Property(23, int.class, "jktj_ysxg", false, "JKTJ_YSXG");
        public final static Property Jktj_xyzt = new Property(24, int.class, "jktj_xyzt", false, "JKTJ_XYZT");
        public final static Property Jktj_rxyl = new Property(25, String.class, "jktj_rxyl", false, "JKTJ_RXYL");
        public final static Property Jktj_ksxy = new Property(26, String.class, "jktj_ksxy", false, "JKTJ_KSXY");
        public final static Property Jktj_jynl = new Property(27, String.class, "jktj_jynl", false, "JKTJ_JYNL");
        public final static Property Jktj_yjpl = new Property(28, int.class, "jktj_yjpl", false, "JKTJ_YJPL");
        public final static Property Jktj_ryjl = new Property(29, String.class, "jktj_ryjl", false, "JKTJ_RYJL");
        public final static Property Jktj_jiej = new Property(30, int.class, "jktj_jiej", false, "JKTJ_JIEJ");
        public final static Property Jktj_jjnl = new Property(31, String.class, "jktj_jjnl", false, "JKTJ_JJNL");
        public final static Property Jktj_ksyj = new Property(32, String.class, "jktj_ksyj", false, "JKTJ_KSYJ");
        public final static Property Jktj_jnzj = new Property(33, int.class, "jktj_jnzj", false, "JKTJ_JNZJ");
        public final static Property Jktj_yjzl = new Property(34, int.class, "jktj_yjzl", false, "JKTJ_YJZL");
        public final static Property Jktj_zyb = new Property(35, int.class, "jktj_zyb", false, "JKTJ_ZYB");
        public final static Property Jktj_zyb_gz = new Property(36, String.class, "jktj_zyb_gz", false, "JKTJ_ZYB_GZ");
        public final static Property Jktj_zyb_cysj = new Property(37, String.class, "jktj_zyb_cysj", false, "JKTJ_ZYB_CYSJ");
        public final static Property Jktj_zyb_fc = new Property(38, String.class, "jktj_zyb_fc", false, "JKTJ_ZYB_FC");
        public final static Property Jktj_zyb_fc_fh = new Property(39, int.class, "jktj_zyb_fc_fh", false, "JKTJ_ZYB_FC_FH");
        public final static Property Jktj_zyb_fc_ms = new Property(40, String.class, "jktj_zyb_fc_ms", false, "JKTJ_ZYB_FC_MS");
        public final static Property Jktj_zyb_fswz = new Property(41, String.class, "jktj_zyb_fswz", false, "JKTJ_ZYB_FSWZ");
        public final static Property Jktj_zyb_fswz_fh = new Property(42, int.class, "jktj_zyb_fswz_fh", false, "JKTJ_ZYB_FSWZ_FH");
        public final static Property Jktj_zyb_fswz_ms = new Property(43, String.class, "jktj_zyb_fswz_ms", false, "JKTJ_ZYB_FSWZ_MS");
        public final static Property Jktj_zyb_wlys = new Property(44, String.class, "jktj_zyb_wlys", false, "JKTJ_ZYB_WLYS");
        public final static Property Jktj_zyb_wlys_fh = new Property(45, int.class, "jktj_zyb_wlys_fh", false, "JKTJ_ZYB_WLYS_FH");
        public final static Property Jktj_zyb_wlys_ms = new Property(46, String.class, "jktj_zyb_wlys_ms", false, "JKTJ_ZYB_WLYS_MS");
        public final static Property Jktj_zyb_hxwz = new Property(47, String.class, "jktj_zyb_hxwz", false, "JKTJ_ZYB_HXWZ");
        public final static Property Jktj_zyb_hxwz_fh = new Property(48, int.class, "jktj_zyb_hxwz_fh", false, "JKTJ_ZYB_HXWZ_FH");
        public final static Property Jktj_zyb_hxwz_ms = new Property(49, String.class, "jktj_zyb_hxwz_ms", false, "JKTJ_ZYB_HXWZ_MS");
        public final static Property Jktj_zyb_other = new Property(50, String.class, "jktj_zyb_other", false, "JKTJ_ZYB_OTHER");
        public final static Property Jktj_zyb_other_fh = new Property(51, int.class, "jktj_zyb_other_fh", false, "JKTJ_ZYB_OTHER_FH");
        public final static Property Jktj_zyb_other_ms = new Property(52, String.class, "jktj_zyb_other_ms", false, "JKTJ_ZYB_OTHER_MS");
        public final static Property CreateDate = new Property(53, String.class, "createDate", false, "CREATE_DATE");
    }


    public JianKangTiJianBiao_ADao(DaoConfig config) {
        super(config);
    }
    
    public JianKangTiJianBiao_ADao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JIAN_KANG_TI_JIAN_BIAO__A\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JKTJ_ID\" TEXT NOT NULL ," + // 1: jktj_id
                "\"NA_ID\" TEXT NOT NULL ," + // 2: na_id
                "\"JKTJ_DATE\" TEXT," + // 3: jktj_date
                "\"JKTJ_DOCTOR\" TEXT," + // 4: jktj_doctor
                "\"SYMPTOM_ID\" INTEGER NOT NULL ," + // 5: symptom_id
                "\"JKTJ_TW\" TEXT," + // 6: jktj_tw
                "\"JKTJ_ML\" TEXT," + // 7: jktj_ml
                "\"JKTJ_HXPL\" TEXT," + // 8: jktj_hxpl
                "\"ZBP_ID\" TEXT," + // 9: zbp_id
                "\"YBP_ID\" TEXT," + // 10: ybp_id
                "\"HW_ID\" TEXT," + // 11: hw_id
                "\"JKTJ_YAOW\" TEXT," + // 12: jktj_yaow
                "\"JKTJ_LNRJK\" INTEGER NOT NULL ," + // 13: jktj_lnrjk
                "\"JKTJ_LNRZL\" INTEGER NOT NULL ," + // 14: jktj_lnrzl
                "\"JKTJ_LNRRZ\" INTEGER NOT NULL ," + // 15: jktj_lnrrz
                "\"JKTJ_ZLZT\" TEXT," + // 16: jktj_zlzt
                "\"JKTJ_LNRQG\" INTEGER NOT NULL ," + // 17: jktj_lnrqg
                "\"JKTJ_LNRYY\" TEXT," + // 18: jktj_lnryy
                "\"JKTJ_DLPL\" INTEGER NOT NULL ," + // 19: jktj_dlpl
                "\"JKTJ_DLSJ\" TEXT," + // 20: jktj_dlsj
                "\"JKTJ_JCSJ\" TEXT," + // 21: jktj_jcsj
                "\"JKTJ_DLFS\" TEXT," + // 22: jktj_dlfs
                "\"JKTJ_YSXG\" INTEGER NOT NULL ," + // 23: jktj_ysxg
                "\"JKTJ_XYZT\" INTEGER NOT NULL ," + // 24: jktj_xyzt
                "\"JKTJ_RXYL\" TEXT," + // 25: jktj_rxyl
                "\"JKTJ_KSXY\" TEXT," + // 26: jktj_ksxy
                "\"JKTJ_JYNL\" TEXT," + // 27: jktj_jynl
                "\"JKTJ_YJPL\" INTEGER NOT NULL ," + // 28: jktj_yjpl
                "\"JKTJ_RYJL\" TEXT," + // 29: jktj_ryjl
                "\"JKTJ_JIEJ\" INTEGER NOT NULL ," + // 30: jktj_jiej
                "\"JKTJ_JJNL\" TEXT," + // 31: jktj_jjnl
                "\"JKTJ_KSYJ\" TEXT," + // 32: jktj_ksyj
                "\"JKTJ_JNZJ\" INTEGER NOT NULL ," + // 33: jktj_jnzj
                "\"JKTJ_YJZL\" INTEGER NOT NULL ," + // 34: jktj_yjzl
                "\"JKTJ_ZYB\" INTEGER NOT NULL ," + // 35: jktj_zyb
                "\"JKTJ_ZYB_GZ\" TEXT," + // 36: jktj_zyb_gz
                "\"JKTJ_ZYB_CYSJ\" TEXT," + // 37: jktj_zyb_cysj
                "\"JKTJ_ZYB_FC\" TEXT," + // 38: jktj_zyb_fc
                "\"JKTJ_ZYB_FC_FH\" INTEGER NOT NULL ," + // 39: jktj_zyb_fc_fh
                "\"JKTJ_ZYB_FC_MS\" TEXT," + // 40: jktj_zyb_fc_ms
                "\"JKTJ_ZYB_FSWZ\" TEXT," + // 41: jktj_zyb_fswz
                "\"JKTJ_ZYB_FSWZ_FH\" INTEGER NOT NULL ," + // 42: jktj_zyb_fswz_fh
                "\"JKTJ_ZYB_FSWZ_MS\" TEXT," + // 43: jktj_zyb_fswz_ms
                "\"JKTJ_ZYB_WLYS\" TEXT," + // 44: jktj_zyb_wlys
                "\"JKTJ_ZYB_WLYS_FH\" INTEGER NOT NULL ," + // 45: jktj_zyb_wlys_fh
                "\"JKTJ_ZYB_WLYS_MS\" TEXT," + // 46: jktj_zyb_wlys_ms
                "\"JKTJ_ZYB_HXWZ\" TEXT," + // 47: jktj_zyb_hxwz
                "\"JKTJ_ZYB_HXWZ_FH\" INTEGER NOT NULL ," + // 48: jktj_zyb_hxwz_fh
                "\"JKTJ_ZYB_HXWZ_MS\" TEXT," + // 49: jktj_zyb_hxwz_ms
                "\"JKTJ_ZYB_OTHER\" TEXT," + // 50: jktj_zyb_other
                "\"JKTJ_ZYB_OTHER_FH\" INTEGER NOT NULL ," + // 51: jktj_zyb_other_fh
                "\"JKTJ_ZYB_OTHER_MS\" TEXT," + // 52: jktj_zyb_other_ms
                "\"CREATE_DATE\" TEXT);"); // 53: createDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JIAN_KANG_TI_JIAN_BIAO__A\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JianKangTiJianBiao_A entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJktj_id());
        stmt.bindString(3, entity.getNa_id());
 
        String jktj_date = entity.getJktj_date();
        if (jktj_date != null) {
            stmt.bindString(4, jktj_date);
        }
 
        String jktj_doctor = entity.getJktj_doctor();
        if (jktj_doctor != null) {
            stmt.bindString(5, jktj_doctor);
        }
        stmt.bindLong(6, entity.getSymptom_id());
 
        String jktj_tw = entity.getJktj_tw();
        if (jktj_tw != null) {
            stmt.bindString(7, jktj_tw);
        }
 
        String jktj_ml = entity.getJktj_ml();
        if (jktj_ml != null) {
            stmt.bindString(8, jktj_ml);
        }
 
        String jktj_hxpl = entity.getJktj_hxpl();
        if (jktj_hxpl != null) {
            stmt.bindString(9, jktj_hxpl);
        }
 
        String zbp_id = entity.getZbp_id();
        if (zbp_id != null) {
            stmt.bindString(10, zbp_id);
        }
 
        String ybp_id = entity.getYbp_id();
        if (ybp_id != null) {
            stmt.bindString(11, ybp_id);
        }
 
        String hw_id = entity.getHw_id();
        if (hw_id != null) {
            stmt.bindString(12, hw_id);
        }
 
        String jktj_yaow = entity.getJktj_yaow();
        if (jktj_yaow != null) {
            stmt.bindString(13, jktj_yaow);
        }
        stmt.bindLong(14, entity.getJktj_lnrjk());
        stmt.bindLong(15, entity.getJktj_lnrzl());
        stmt.bindLong(16, entity.getJktj_lnrrz());
 
        String jktj_zlzt = entity.getJktj_zlzt();
        if (jktj_zlzt != null) {
            stmt.bindString(17, jktj_zlzt);
        }
        stmt.bindLong(18, entity.getJktj_lnrqg());
 
        String jktj_lnryy = entity.getJktj_lnryy();
        if (jktj_lnryy != null) {
            stmt.bindString(19, jktj_lnryy);
        }
        stmt.bindLong(20, entity.getJktj_dlpl());
 
        String jktj_dlsj = entity.getJktj_dlsj();
        if (jktj_dlsj != null) {
            stmt.bindString(21, jktj_dlsj);
        }
 
        String jktj_jcsj = entity.getJktj_jcsj();
        if (jktj_jcsj != null) {
            stmt.bindString(22, jktj_jcsj);
        }
 
        String jktj_dlfs = entity.getJktj_dlfs();
        if (jktj_dlfs != null) {
            stmt.bindString(23, jktj_dlfs);
        }
        stmt.bindLong(24, entity.getJktj_ysxg());
        stmt.bindLong(25, entity.getJktj_xyzt());
 
        String jktj_rxyl = entity.getJktj_rxyl();
        if (jktj_rxyl != null) {
            stmt.bindString(26, jktj_rxyl);
        }
 
        String jktj_ksxy = entity.getJktj_ksxy();
        if (jktj_ksxy != null) {
            stmt.bindString(27, jktj_ksxy);
        }
 
        String jktj_jynl = entity.getJktj_jynl();
        if (jktj_jynl != null) {
            stmt.bindString(28, jktj_jynl);
        }
        stmt.bindLong(29, entity.getJktj_yjpl());
 
        String jktj_ryjl = entity.getJktj_ryjl();
        if (jktj_ryjl != null) {
            stmt.bindString(30, jktj_ryjl);
        }
        stmt.bindLong(31, entity.getJktj_jiej());
 
        String jktj_jjnl = entity.getJktj_jjnl();
        if (jktj_jjnl != null) {
            stmt.bindString(32, jktj_jjnl);
        }
 
        String jktj_ksyj = entity.getJktj_ksyj();
        if (jktj_ksyj != null) {
            stmt.bindString(33, jktj_ksyj);
        }
        stmt.bindLong(34, entity.getJktj_jnzj());
        stmt.bindLong(35, entity.getJktj_yjzl());
        stmt.bindLong(36, entity.getJktj_zyb());
 
        String jktj_zyb_gz = entity.getJktj_zyb_gz();
        if (jktj_zyb_gz != null) {
            stmt.bindString(37, jktj_zyb_gz);
        }
 
        String jktj_zyb_cysj = entity.getJktj_zyb_cysj();
        if (jktj_zyb_cysj != null) {
            stmt.bindString(38, jktj_zyb_cysj);
        }
 
        String jktj_zyb_fc = entity.getJktj_zyb_fc();
        if (jktj_zyb_fc != null) {
            stmt.bindString(39, jktj_zyb_fc);
        }
        stmt.bindLong(40, entity.getJktj_zyb_fc_fh());
 
        String jktj_zyb_fc_ms = entity.getJktj_zyb_fc_ms();
        if (jktj_zyb_fc_ms != null) {
            stmt.bindString(41, jktj_zyb_fc_ms);
        }
 
        String jktj_zyb_fswz = entity.getJktj_zyb_fswz();
        if (jktj_zyb_fswz != null) {
            stmt.bindString(42, jktj_zyb_fswz);
        }
        stmt.bindLong(43, entity.getJktj_zyb_fswz_fh());
 
        String jktj_zyb_fswz_ms = entity.getJktj_zyb_fswz_ms();
        if (jktj_zyb_fswz_ms != null) {
            stmt.bindString(44, jktj_zyb_fswz_ms);
        }
 
        String jktj_zyb_wlys = entity.getJktj_zyb_wlys();
        if (jktj_zyb_wlys != null) {
            stmt.bindString(45, jktj_zyb_wlys);
        }
        stmt.bindLong(46, entity.getJktj_zyb_wlys_fh());
 
        String jktj_zyb_wlys_ms = entity.getJktj_zyb_wlys_ms();
        if (jktj_zyb_wlys_ms != null) {
            stmt.bindString(47, jktj_zyb_wlys_ms);
        }
 
        String jktj_zyb_hxwz = entity.getJktj_zyb_hxwz();
        if (jktj_zyb_hxwz != null) {
            stmt.bindString(48, jktj_zyb_hxwz);
        }
        stmt.bindLong(49, entity.getJktj_zyb_hxwz_fh());
 
        String jktj_zyb_hxwz_ms = entity.getJktj_zyb_hxwz_ms();
        if (jktj_zyb_hxwz_ms != null) {
            stmt.bindString(50, jktj_zyb_hxwz_ms);
        }
 
        String jktj_zyb_other = entity.getJktj_zyb_other();
        if (jktj_zyb_other != null) {
            stmt.bindString(51, jktj_zyb_other);
        }
        stmt.bindLong(52, entity.getJktj_zyb_other_fh());
 
        String jktj_zyb_other_ms = entity.getJktj_zyb_other_ms();
        if (jktj_zyb_other_ms != null) {
            stmt.bindString(53, jktj_zyb_other_ms);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(54, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JianKangTiJianBiao_A entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJktj_id());
        stmt.bindString(3, entity.getNa_id());
 
        String jktj_date = entity.getJktj_date();
        if (jktj_date != null) {
            stmt.bindString(4, jktj_date);
        }
 
        String jktj_doctor = entity.getJktj_doctor();
        if (jktj_doctor != null) {
            stmt.bindString(5, jktj_doctor);
        }
        stmt.bindLong(6, entity.getSymptom_id());
 
        String jktj_tw = entity.getJktj_tw();
        if (jktj_tw != null) {
            stmt.bindString(7, jktj_tw);
        }
 
        String jktj_ml = entity.getJktj_ml();
        if (jktj_ml != null) {
            stmt.bindString(8, jktj_ml);
        }
 
        String jktj_hxpl = entity.getJktj_hxpl();
        if (jktj_hxpl != null) {
            stmt.bindString(9, jktj_hxpl);
        }
 
        String zbp_id = entity.getZbp_id();
        if (zbp_id != null) {
            stmt.bindString(10, zbp_id);
        }
 
        String ybp_id = entity.getYbp_id();
        if (ybp_id != null) {
            stmt.bindString(11, ybp_id);
        }
 
        String hw_id = entity.getHw_id();
        if (hw_id != null) {
            stmt.bindString(12, hw_id);
        }
 
        String jktj_yaow = entity.getJktj_yaow();
        if (jktj_yaow != null) {
            stmt.bindString(13, jktj_yaow);
        }
        stmt.bindLong(14, entity.getJktj_lnrjk());
        stmt.bindLong(15, entity.getJktj_lnrzl());
        stmt.bindLong(16, entity.getJktj_lnrrz());
 
        String jktj_zlzt = entity.getJktj_zlzt();
        if (jktj_zlzt != null) {
            stmt.bindString(17, jktj_zlzt);
        }
        stmt.bindLong(18, entity.getJktj_lnrqg());
 
        String jktj_lnryy = entity.getJktj_lnryy();
        if (jktj_lnryy != null) {
            stmt.bindString(19, jktj_lnryy);
        }
        stmt.bindLong(20, entity.getJktj_dlpl());
 
        String jktj_dlsj = entity.getJktj_dlsj();
        if (jktj_dlsj != null) {
            stmt.bindString(21, jktj_dlsj);
        }
 
        String jktj_jcsj = entity.getJktj_jcsj();
        if (jktj_jcsj != null) {
            stmt.bindString(22, jktj_jcsj);
        }
 
        String jktj_dlfs = entity.getJktj_dlfs();
        if (jktj_dlfs != null) {
            stmt.bindString(23, jktj_dlfs);
        }
        stmt.bindLong(24, entity.getJktj_ysxg());
        stmt.bindLong(25, entity.getJktj_xyzt());
 
        String jktj_rxyl = entity.getJktj_rxyl();
        if (jktj_rxyl != null) {
            stmt.bindString(26, jktj_rxyl);
        }
 
        String jktj_ksxy = entity.getJktj_ksxy();
        if (jktj_ksxy != null) {
            stmt.bindString(27, jktj_ksxy);
        }
 
        String jktj_jynl = entity.getJktj_jynl();
        if (jktj_jynl != null) {
            stmt.bindString(28, jktj_jynl);
        }
        stmt.bindLong(29, entity.getJktj_yjpl());
 
        String jktj_ryjl = entity.getJktj_ryjl();
        if (jktj_ryjl != null) {
            stmt.bindString(30, jktj_ryjl);
        }
        stmt.bindLong(31, entity.getJktj_jiej());
 
        String jktj_jjnl = entity.getJktj_jjnl();
        if (jktj_jjnl != null) {
            stmt.bindString(32, jktj_jjnl);
        }
 
        String jktj_ksyj = entity.getJktj_ksyj();
        if (jktj_ksyj != null) {
            stmt.bindString(33, jktj_ksyj);
        }
        stmt.bindLong(34, entity.getJktj_jnzj());
        stmt.bindLong(35, entity.getJktj_yjzl());
        stmt.bindLong(36, entity.getJktj_zyb());
 
        String jktj_zyb_gz = entity.getJktj_zyb_gz();
        if (jktj_zyb_gz != null) {
            stmt.bindString(37, jktj_zyb_gz);
        }
 
        String jktj_zyb_cysj = entity.getJktj_zyb_cysj();
        if (jktj_zyb_cysj != null) {
            stmt.bindString(38, jktj_zyb_cysj);
        }
 
        String jktj_zyb_fc = entity.getJktj_zyb_fc();
        if (jktj_zyb_fc != null) {
            stmt.bindString(39, jktj_zyb_fc);
        }
        stmt.bindLong(40, entity.getJktj_zyb_fc_fh());
 
        String jktj_zyb_fc_ms = entity.getJktj_zyb_fc_ms();
        if (jktj_zyb_fc_ms != null) {
            stmt.bindString(41, jktj_zyb_fc_ms);
        }
 
        String jktj_zyb_fswz = entity.getJktj_zyb_fswz();
        if (jktj_zyb_fswz != null) {
            stmt.bindString(42, jktj_zyb_fswz);
        }
        stmt.bindLong(43, entity.getJktj_zyb_fswz_fh());
 
        String jktj_zyb_fswz_ms = entity.getJktj_zyb_fswz_ms();
        if (jktj_zyb_fswz_ms != null) {
            stmt.bindString(44, jktj_zyb_fswz_ms);
        }
 
        String jktj_zyb_wlys = entity.getJktj_zyb_wlys();
        if (jktj_zyb_wlys != null) {
            stmt.bindString(45, jktj_zyb_wlys);
        }
        stmt.bindLong(46, entity.getJktj_zyb_wlys_fh());
 
        String jktj_zyb_wlys_ms = entity.getJktj_zyb_wlys_ms();
        if (jktj_zyb_wlys_ms != null) {
            stmt.bindString(47, jktj_zyb_wlys_ms);
        }
 
        String jktj_zyb_hxwz = entity.getJktj_zyb_hxwz();
        if (jktj_zyb_hxwz != null) {
            stmt.bindString(48, jktj_zyb_hxwz);
        }
        stmt.bindLong(49, entity.getJktj_zyb_hxwz_fh());
 
        String jktj_zyb_hxwz_ms = entity.getJktj_zyb_hxwz_ms();
        if (jktj_zyb_hxwz_ms != null) {
            stmt.bindString(50, jktj_zyb_hxwz_ms);
        }
 
        String jktj_zyb_other = entity.getJktj_zyb_other();
        if (jktj_zyb_other != null) {
            stmt.bindString(51, jktj_zyb_other);
        }
        stmt.bindLong(52, entity.getJktj_zyb_other_fh());
 
        String jktj_zyb_other_ms = entity.getJktj_zyb_other_ms();
        if (jktj_zyb_other_ms != null) {
            stmt.bindString(53, jktj_zyb_other_ms);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(54, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JianKangTiJianBiao_A readEntity(Cursor cursor, int offset) {
        JianKangTiJianBiao_A entity = new JianKangTiJianBiao_A( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // jktj_id
            cursor.getString(offset + 2), // na_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // jktj_date
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // jktj_doctor
            cursor.getInt(offset + 5), // symptom_id
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // jktj_tw
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // jktj_ml
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // jktj_hxpl
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // zbp_id
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // ybp_id
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // hw_id
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // jktj_yaow
            cursor.getInt(offset + 13), // jktj_lnrjk
            cursor.getInt(offset + 14), // jktj_lnrzl
            cursor.getInt(offset + 15), // jktj_lnrrz
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // jktj_zlzt
            cursor.getInt(offset + 17), // jktj_lnrqg
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // jktj_lnryy
            cursor.getInt(offset + 19), // jktj_dlpl
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // jktj_dlsj
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // jktj_jcsj
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // jktj_dlfs
            cursor.getInt(offset + 23), // jktj_ysxg
            cursor.getInt(offset + 24), // jktj_xyzt
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // jktj_rxyl
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // jktj_ksxy
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // jktj_jynl
            cursor.getInt(offset + 28), // jktj_yjpl
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // jktj_ryjl
            cursor.getInt(offset + 30), // jktj_jiej
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // jktj_jjnl
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // jktj_ksyj
            cursor.getInt(offset + 33), // jktj_jnzj
            cursor.getInt(offset + 34), // jktj_yjzl
            cursor.getInt(offset + 35), // jktj_zyb
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // jktj_zyb_gz
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // jktj_zyb_cysj
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // jktj_zyb_fc
            cursor.getInt(offset + 39), // jktj_zyb_fc_fh
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // jktj_zyb_fc_ms
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // jktj_zyb_fswz
            cursor.getInt(offset + 42), // jktj_zyb_fswz_fh
            cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43), // jktj_zyb_fswz_ms
            cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44), // jktj_zyb_wlys
            cursor.getInt(offset + 45), // jktj_zyb_wlys_fh
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // jktj_zyb_wlys_ms
            cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47), // jktj_zyb_hxwz
            cursor.getInt(offset + 48), // jktj_zyb_hxwz_fh
            cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49), // jktj_zyb_hxwz_ms
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // jktj_zyb_other
            cursor.getInt(offset + 51), // jktj_zyb_other_fh
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // jktj_zyb_other_ms
            cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JianKangTiJianBiao_A entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJktj_id(cursor.getString(offset + 1));
        entity.setNa_id(cursor.getString(offset + 2));
        entity.setJktj_date(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJktj_doctor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSymptom_id(cursor.getInt(offset + 5));
        entity.setJktj_tw(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJktj_ml(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setJktj_hxpl(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setZbp_id(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setYbp_id(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setHw_id(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setJktj_yaow(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setJktj_lnrjk(cursor.getInt(offset + 13));
        entity.setJktj_lnrzl(cursor.getInt(offset + 14));
        entity.setJktj_lnrrz(cursor.getInt(offset + 15));
        entity.setJktj_zlzt(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setJktj_lnrqg(cursor.getInt(offset + 17));
        entity.setJktj_lnryy(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setJktj_dlpl(cursor.getInt(offset + 19));
        entity.setJktj_dlsj(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setJktj_jcsj(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setJktj_dlfs(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setJktj_ysxg(cursor.getInt(offset + 23));
        entity.setJktj_xyzt(cursor.getInt(offset + 24));
        entity.setJktj_rxyl(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setJktj_ksxy(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setJktj_jynl(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setJktj_yjpl(cursor.getInt(offset + 28));
        entity.setJktj_ryjl(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setJktj_jiej(cursor.getInt(offset + 30));
        entity.setJktj_jjnl(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setJktj_ksyj(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setJktj_jnzj(cursor.getInt(offset + 33));
        entity.setJktj_yjzl(cursor.getInt(offset + 34));
        entity.setJktj_zyb(cursor.getInt(offset + 35));
        entity.setJktj_zyb_gz(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setJktj_zyb_cysj(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setJktj_zyb_fc(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setJktj_zyb_fc_fh(cursor.getInt(offset + 39));
        entity.setJktj_zyb_fc_ms(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setJktj_zyb_fswz(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setJktj_zyb_fswz_fh(cursor.getInt(offset + 42));
        entity.setJktj_zyb_fswz_ms(cursor.isNull(offset + 43) ? null : cursor.getString(offset + 43));
        entity.setJktj_zyb_wlys(cursor.isNull(offset + 44) ? null : cursor.getString(offset + 44));
        entity.setJktj_zyb_wlys_fh(cursor.getInt(offset + 45));
        entity.setJktj_zyb_wlys_ms(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setJktj_zyb_hxwz(cursor.isNull(offset + 47) ? null : cursor.getString(offset + 47));
        entity.setJktj_zyb_hxwz_fh(cursor.getInt(offset + 48));
        entity.setJktj_zyb_hxwz_ms(cursor.isNull(offset + 49) ? null : cursor.getString(offset + 49));
        entity.setJktj_zyb_other(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setJktj_zyb_other_fh(cursor.getInt(offset + 51));
        entity.setJktj_zyb_other_ms(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setCreateDate(cursor.isNull(offset + 53) ? null : cursor.getString(offset + 53));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JianKangTiJianBiao_A entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JianKangTiJianBiao_A entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JianKangTiJianBiao_A entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
