package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.JianKangTiJianBiao_D;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JIAN_KANG_TI_JIAN_BIAO__D".
*/
public class JianKangTiJianBiao_DDao extends AbstractDao<JianKangTiJianBiao_D, Long> {

    public static final String TABLENAME = "JIAN_KANG_TI_JIAN_BIAO__D";

    /**
     * Properties of entity JianKangTiJianBiao_D.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Jktj3_id = new Property(1, String.class, "jktj3_id", false, "JKTJ3_ID");
        public final static Property Jktj_id = new Property(2, String.class, "jktj_id", false, "JKTJ_ID");
        public final static Property Jktj3_xcg_xhdb = new Property(3, String.class, "jktj3_xcg_xhdb", false, "JKTJ3_XCG_XHDB");
        public final static Property Jktj3_xcg_bxb = new Property(4, String.class, "jktj3_xcg_bxb", false, "JKTJ3_XCG_BXB");
        public final static Property Jktj3_xcg_xxb = new Property(5, String.class, "jktj3_xcg_xxb", false, "JKTJ3_XCG_XXB");
        public final static Property Jktj3_xcg_other = new Property(6, String.class, "jktj3_xcg_other", false, "JKTJ3_XCG_OTHER");
        public final static Property Jktj3_ncg_ndb = new Property(7, String.class, "jktj3_ncg_ndb", false, "JKTJ3_NCG_NDB");
        public final static Property Jktj3_ncg_nt = new Property(8, String.class, "jktj3_ncg_nt", false, "JKTJ3_NCG_NT");
        public final static Property Jktj3_ncg_ntt = new Property(9, String.class, "jktj3_ncg_ntt", false, "JKTJ3_NCG_NTT");
        public final static Property Jktj3_ncg_nqx = new Property(10, String.class, "jktj3_ncg_nqx", false, "JKTJ3_NCG_NQX");
        public final static Property Jktj3_ncg_other = new Property(11, String.class, "jktj3_ncg_other", false, "JKTJ3_NCG_OTHER");
        public final static Property Jktj3_kfxt = new Property(12, String.class, "jktj3_kfxt", false, "JKTJ3_KFXT");
        public final static Property Jktj3_kfxt1 = new Property(13, String.class, "jktj3_kfxt1", false, "JKTJ3_KFXT1");
        public final static Property Jktj3_xdt = new Property(14, int.class, "jktj3_xdt", false, "JKTJ3_XDT");
        public final static Property Jktj3_xdt_ms = new Property(15, String.class, "jktj3_xdt_ms", false, "JKTJ3_XDT_MS");
        public final static Property Jktj3_nwlbdb = new Property(16, String.class, "jktj3_nwlbdb", false, "JKTJ3_NWLBDB");
        public final static Property Jktj3_dbqx = new Property(17, int.class, "jktj3_dbqx", false, "JKTJ3_DBQX");
        public final static Property Jktj3_thxhdb = new Property(18, String.class, "jktj3_thxhdb", false, "JKTJ3_THXHDB");
        public final static Property Jktj3_yxgy = new Property(19, int.class, "jktj3_yxgy", false, "JKTJ3_YXGY");
        public final static Property Jktj3_gan_xqgb = new Property(20, String.class, "jktj3_gan_xqgb", false, "JKTJ3_GAN_XQGB");
        public final static Property Jktj3_gan_xqgc = new Property(21, String.class, "jktj3_gan_xqgc", false, "JKTJ3_GAN_XQGC");
        public final static Property Jktj3_gan_bdb = new Property(22, String.class, "jktj3_gan_bdb", false, "JKTJ3_GAN_BDB");
        public final static Property Jktj3_gan_zdhs = new Property(23, String.class, "jktj3_gan_zdhs", false, "JKTJ3_GAN_ZDHS");
        public final static Property Jktj3_gan_zhdhs = new Property(24, String.class, "jktj3_gan_zhdhs", false, "JKTJ3_GAN_ZHDHS");
        public final static Property Jktj3_sen_xqjg = new Property(25, String.class, "jktj3_sen_xqjg", false, "JKTJ3_SEN_XQJG");
        public final static Property Jktj3_sen_xnsd = new Property(26, String.class, "jktj3_sen_xnsd", false, "JKTJ3_SEN_XNSD");
        public final static Property Jktj3_sen_xj = new Property(27, String.class, "jktj3_sen_xj", false, "JKTJ3_SEN_XJ");
        public final static Property Jktj3_sen_xn = new Property(28, String.class, "jktj3_sen_xn", false, "JKTJ3_SEN_XN");
        public final static Property Jktj3_xz_zdgc = new Property(29, String.class, "jktj3_xz_zdgc", false, "JKTJ3_XZ_ZDGC");
        public final static Property Jktj3_xz_gysz = new Property(30, String.class, "jktj3_xz_gysz", false, "JKTJ3_XZ_GYSZ");
        public final static Property Jktj3_xz_dmd = new Property(31, String.class, "jktj3_xz_dmd", false, "JKTJ3_XZ_DMD");
        public final static Property Jktj3_xz_gmd = new Property(32, String.class, "jktj3_xz_gmd", false, "JKTJ3_XZ_GMD");
        public final static Property Jktj3_xb = new Property(33, int.class, "jktj3_xb", false, "JKTJ3_XB");
        public final static Property Jktj3_xb_ms = new Property(34, String.class, "jktj3_xb_ms", false, "JKTJ3_XB_MS");
        public final static Property Jktj3_bc = new Property(35, int.class, "jktj3_bc", false, "JKTJ3_BC");
        public final static Property Jktj3_bc_ms = new Property(36, String.class, "jktj3_bc_ms", false, "JKTJ3_BC_MS");
        public final static Property Jktj3_gj = new Property(37, int.class, "jktj3_gj", false, "JKTJ3_GJ");
        public final static Property Jktj3_gj_ms = new Property(38, String.class, "jktj3_gj_ms", false, "JKTJ3_GJ_MS");
        public final static Property Jktj3_bz = new Property(39, String.class, "jktj3_bz", false, "JKTJ3_BZ");
        public final static Property CreateDate = new Property(40, String.class, "createDate", false, "CREATE_DATE");
    }


    public JianKangTiJianBiao_DDao(DaoConfig config) {
        super(config);
    }
    
    public JianKangTiJianBiao_DDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JIAN_KANG_TI_JIAN_BIAO__D\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JKTJ3_ID\" TEXT NOT NULL ," + // 1: jktj3_id
                "\"JKTJ_ID\" TEXT NOT NULL ," + // 2: jktj_id
                "\"JKTJ3_XCG_XHDB\" TEXT," + // 3: jktj3_xcg_xhdb
                "\"JKTJ3_XCG_BXB\" TEXT," + // 4: jktj3_xcg_bxb
                "\"JKTJ3_XCG_XXB\" TEXT," + // 5: jktj3_xcg_xxb
                "\"JKTJ3_XCG_OTHER\" TEXT," + // 6: jktj3_xcg_other
                "\"JKTJ3_NCG_NDB\" TEXT," + // 7: jktj3_ncg_ndb
                "\"JKTJ3_NCG_NT\" TEXT," + // 8: jktj3_ncg_nt
                "\"JKTJ3_NCG_NTT\" TEXT," + // 9: jktj3_ncg_ntt
                "\"JKTJ3_NCG_NQX\" TEXT," + // 10: jktj3_ncg_nqx
                "\"JKTJ3_NCG_OTHER\" TEXT," + // 11: jktj3_ncg_other
                "\"JKTJ3_KFXT\" TEXT," + // 12: jktj3_kfxt
                "\"JKTJ3_KFXT1\" TEXT," + // 13: jktj3_kfxt1
                "\"JKTJ3_XDT\" INTEGER NOT NULL ," + // 14: jktj3_xdt
                "\"JKTJ3_XDT_MS\" TEXT," + // 15: jktj3_xdt_ms
                "\"JKTJ3_NWLBDB\" TEXT," + // 16: jktj3_nwlbdb
                "\"JKTJ3_DBQX\" INTEGER NOT NULL ," + // 17: jktj3_dbqx
                "\"JKTJ3_THXHDB\" TEXT," + // 18: jktj3_thxhdb
                "\"JKTJ3_YXGY\" INTEGER NOT NULL ," + // 19: jktj3_yxgy
                "\"JKTJ3_GAN_XQGB\" TEXT," + // 20: jktj3_gan_xqgb
                "\"JKTJ3_GAN_XQGC\" TEXT," + // 21: jktj3_gan_xqgc
                "\"JKTJ3_GAN_BDB\" TEXT," + // 22: jktj3_gan_bdb
                "\"JKTJ3_GAN_ZDHS\" TEXT," + // 23: jktj3_gan_zdhs
                "\"JKTJ3_GAN_ZHDHS\" TEXT," + // 24: jktj3_gan_zhdhs
                "\"JKTJ3_SEN_XQJG\" TEXT," + // 25: jktj3_sen_xqjg
                "\"JKTJ3_SEN_XNSD\" TEXT," + // 26: jktj3_sen_xnsd
                "\"JKTJ3_SEN_XJ\" TEXT," + // 27: jktj3_sen_xj
                "\"JKTJ3_SEN_XN\" TEXT," + // 28: jktj3_sen_xn
                "\"JKTJ3_XZ_ZDGC\" TEXT," + // 29: jktj3_xz_zdgc
                "\"JKTJ3_XZ_GYSZ\" TEXT," + // 30: jktj3_xz_gysz
                "\"JKTJ3_XZ_DMD\" TEXT," + // 31: jktj3_xz_dmd
                "\"JKTJ3_XZ_GMD\" TEXT," + // 32: jktj3_xz_gmd
                "\"JKTJ3_XB\" INTEGER NOT NULL ," + // 33: jktj3_xb
                "\"JKTJ3_XB_MS\" TEXT," + // 34: jktj3_xb_ms
                "\"JKTJ3_BC\" INTEGER NOT NULL ," + // 35: jktj3_bc
                "\"JKTJ3_BC_MS\" TEXT," + // 36: jktj3_bc_ms
                "\"JKTJ3_GJ\" INTEGER NOT NULL ," + // 37: jktj3_gj
                "\"JKTJ3_GJ_MS\" TEXT," + // 38: jktj3_gj_ms
                "\"JKTJ3_BZ\" TEXT," + // 39: jktj3_bz
                "\"CREATE_DATE\" TEXT);"); // 40: createDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JIAN_KANG_TI_JIAN_BIAO__D\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, JianKangTiJianBiao_D entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJktj3_id());
        stmt.bindString(3, entity.getJktj_id());
 
        String jktj3_xcg_xhdb = entity.getJktj3_xcg_xhdb();
        if (jktj3_xcg_xhdb != null) {
            stmt.bindString(4, jktj3_xcg_xhdb);
        }
 
        String jktj3_xcg_bxb = entity.getJktj3_xcg_bxb();
        if (jktj3_xcg_bxb != null) {
            stmt.bindString(5, jktj3_xcg_bxb);
        }
 
        String jktj3_xcg_xxb = entity.getJktj3_xcg_xxb();
        if (jktj3_xcg_xxb != null) {
            stmt.bindString(6, jktj3_xcg_xxb);
        }
 
        String jktj3_xcg_other = entity.getJktj3_xcg_other();
        if (jktj3_xcg_other != null) {
            stmt.bindString(7, jktj3_xcg_other);
        }
 
        String jktj3_ncg_ndb = entity.getJktj3_ncg_ndb();
        if (jktj3_ncg_ndb != null) {
            stmt.bindString(8, jktj3_ncg_ndb);
        }
 
        String jktj3_ncg_nt = entity.getJktj3_ncg_nt();
        if (jktj3_ncg_nt != null) {
            stmt.bindString(9, jktj3_ncg_nt);
        }
 
        String jktj3_ncg_ntt = entity.getJktj3_ncg_ntt();
        if (jktj3_ncg_ntt != null) {
            stmt.bindString(10, jktj3_ncg_ntt);
        }
 
        String jktj3_ncg_nqx = entity.getJktj3_ncg_nqx();
        if (jktj3_ncg_nqx != null) {
            stmt.bindString(11, jktj3_ncg_nqx);
        }
 
        String jktj3_ncg_other = entity.getJktj3_ncg_other();
        if (jktj3_ncg_other != null) {
            stmt.bindString(12, jktj3_ncg_other);
        }
 
        String jktj3_kfxt = entity.getJktj3_kfxt();
        if (jktj3_kfxt != null) {
            stmt.bindString(13, jktj3_kfxt);
        }
 
        String jktj3_kfxt1 = entity.getJktj3_kfxt1();
        if (jktj3_kfxt1 != null) {
            stmt.bindString(14, jktj3_kfxt1);
        }
        stmt.bindLong(15, entity.getJktj3_xdt());
 
        String jktj3_xdt_ms = entity.getJktj3_xdt_ms();
        if (jktj3_xdt_ms != null) {
            stmt.bindString(16, jktj3_xdt_ms);
        }
 
        String jktj3_nwlbdb = entity.getJktj3_nwlbdb();
        if (jktj3_nwlbdb != null) {
            stmt.bindString(17, jktj3_nwlbdb);
        }
        stmt.bindLong(18, entity.getJktj3_dbqx());
 
        String jktj3_thxhdb = entity.getJktj3_thxhdb();
        if (jktj3_thxhdb != null) {
            stmt.bindString(19, jktj3_thxhdb);
        }
        stmt.bindLong(20, entity.getJktj3_yxgy());
 
        String jktj3_gan_xqgb = entity.getJktj3_gan_xqgb();
        if (jktj3_gan_xqgb != null) {
            stmt.bindString(21, jktj3_gan_xqgb);
        }
 
        String jktj3_gan_xqgc = entity.getJktj3_gan_xqgc();
        if (jktj3_gan_xqgc != null) {
            stmt.bindString(22, jktj3_gan_xqgc);
        }
 
        String jktj3_gan_bdb = entity.getJktj3_gan_bdb();
        if (jktj3_gan_bdb != null) {
            stmt.bindString(23, jktj3_gan_bdb);
        }
 
        String jktj3_gan_zdhs = entity.getJktj3_gan_zdhs();
        if (jktj3_gan_zdhs != null) {
            stmt.bindString(24, jktj3_gan_zdhs);
        }
 
        String jktj3_gan_zhdhs = entity.getJktj3_gan_zhdhs();
        if (jktj3_gan_zhdhs != null) {
            stmt.bindString(25, jktj3_gan_zhdhs);
        }
 
        String jktj3_sen_xqjg = entity.getJktj3_sen_xqjg();
        if (jktj3_sen_xqjg != null) {
            stmt.bindString(26, jktj3_sen_xqjg);
        }
 
        String jktj3_sen_xnsd = entity.getJktj3_sen_xnsd();
        if (jktj3_sen_xnsd != null) {
            stmt.bindString(27, jktj3_sen_xnsd);
        }
 
        String jktj3_sen_xj = entity.getJktj3_sen_xj();
        if (jktj3_sen_xj != null) {
            stmt.bindString(28, jktj3_sen_xj);
        }
 
        String jktj3_sen_xn = entity.getJktj3_sen_xn();
        if (jktj3_sen_xn != null) {
            stmt.bindString(29, jktj3_sen_xn);
        }
 
        String jktj3_xz_zdgc = entity.getJktj3_xz_zdgc();
        if (jktj3_xz_zdgc != null) {
            stmt.bindString(30, jktj3_xz_zdgc);
        }
 
        String jktj3_xz_gysz = entity.getJktj3_xz_gysz();
        if (jktj3_xz_gysz != null) {
            stmt.bindString(31, jktj3_xz_gysz);
        }
 
        String jktj3_xz_dmd = entity.getJktj3_xz_dmd();
        if (jktj3_xz_dmd != null) {
            stmt.bindString(32, jktj3_xz_dmd);
        }
 
        String jktj3_xz_gmd = entity.getJktj3_xz_gmd();
        if (jktj3_xz_gmd != null) {
            stmt.bindString(33, jktj3_xz_gmd);
        }
        stmt.bindLong(34, entity.getJktj3_xb());
 
        String jktj3_xb_ms = entity.getJktj3_xb_ms();
        if (jktj3_xb_ms != null) {
            stmt.bindString(35, jktj3_xb_ms);
        }
        stmt.bindLong(36, entity.getJktj3_bc());
 
        String jktj3_bc_ms = entity.getJktj3_bc_ms();
        if (jktj3_bc_ms != null) {
            stmt.bindString(37, jktj3_bc_ms);
        }
        stmt.bindLong(38, entity.getJktj3_gj());
 
        String jktj3_gj_ms = entity.getJktj3_gj_ms();
        if (jktj3_gj_ms != null) {
            stmt.bindString(39, jktj3_gj_ms);
        }
 
        String jktj3_bz = entity.getJktj3_bz();
        if (jktj3_bz != null) {
            stmt.bindString(40, jktj3_bz);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(41, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, JianKangTiJianBiao_D entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getJktj3_id());
        stmt.bindString(3, entity.getJktj_id());
 
        String jktj3_xcg_xhdb = entity.getJktj3_xcg_xhdb();
        if (jktj3_xcg_xhdb != null) {
            stmt.bindString(4, jktj3_xcg_xhdb);
        }
 
        String jktj3_xcg_bxb = entity.getJktj3_xcg_bxb();
        if (jktj3_xcg_bxb != null) {
            stmt.bindString(5, jktj3_xcg_bxb);
        }
 
        String jktj3_xcg_xxb = entity.getJktj3_xcg_xxb();
        if (jktj3_xcg_xxb != null) {
            stmt.bindString(6, jktj3_xcg_xxb);
        }
 
        String jktj3_xcg_other = entity.getJktj3_xcg_other();
        if (jktj3_xcg_other != null) {
            stmt.bindString(7, jktj3_xcg_other);
        }
 
        String jktj3_ncg_ndb = entity.getJktj3_ncg_ndb();
        if (jktj3_ncg_ndb != null) {
            stmt.bindString(8, jktj3_ncg_ndb);
        }
 
        String jktj3_ncg_nt = entity.getJktj3_ncg_nt();
        if (jktj3_ncg_nt != null) {
            stmt.bindString(9, jktj3_ncg_nt);
        }
 
        String jktj3_ncg_ntt = entity.getJktj3_ncg_ntt();
        if (jktj3_ncg_ntt != null) {
            stmt.bindString(10, jktj3_ncg_ntt);
        }
 
        String jktj3_ncg_nqx = entity.getJktj3_ncg_nqx();
        if (jktj3_ncg_nqx != null) {
            stmt.bindString(11, jktj3_ncg_nqx);
        }
 
        String jktj3_ncg_other = entity.getJktj3_ncg_other();
        if (jktj3_ncg_other != null) {
            stmt.bindString(12, jktj3_ncg_other);
        }
 
        String jktj3_kfxt = entity.getJktj3_kfxt();
        if (jktj3_kfxt != null) {
            stmt.bindString(13, jktj3_kfxt);
        }
 
        String jktj3_kfxt1 = entity.getJktj3_kfxt1();
        if (jktj3_kfxt1 != null) {
            stmt.bindString(14, jktj3_kfxt1);
        }
        stmt.bindLong(15, entity.getJktj3_xdt());
 
        String jktj3_xdt_ms = entity.getJktj3_xdt_ms();
        if (jktj3_xdt_ms != null) {
            stmt.bindString(16, jktj3_xdt_ms);
        }
 
        String jktj3_nwlbdb = entity.getJktj3_nwlbdb();
        if (jktj3_nwlbdb != null) {
            stmt.bindString(17, jktj3_nwlbdb);
        }
        stmt.bindLong(18, entity.getJktj3_dbqx());
 
        String jktj3_thxhdb = entity.getJktj3_thxhdb();
        if (jktj3_thxhdb != null) {
            stmt.bindString(19, jktj3_thxhdb);
        }
        stmt.bindLong(20, entity.getJktj3_yxgy());
 
        String jktj3_gan_xqgb = entity.getJktj3_gan_xqgb();
        if (jktj3_gan_xqgb != null) {
            stmt.bindString(21, jktj3_gan_xqgb);
        }
 
        String jktj3_gan_xqgc = entity.getJktj3_gan_xqgc();
        if (jktj3_gan_xqgc != null) {
            stmt.bindString(22, jktj3_gan_xqgc);
        }
 
        String jktj3_gan_bdb = entity.getJktj3_gan_bdb();
        if (jktj3_gan_bdb != null) {
            stmt.bindString(23, jktj3_gan_bdb);
        }
 
        String jktj3_gan_zdhs = entity.getJktj3_gan_zdhs();
        if (jktj3_gan_zdhs != null) {
            stmt.bindString(24, jktj3_gan_zdhs);
        }
 
        String jktj3_gan_zhdhs = entity.getJktj3_gan_zhdhs();
        if (jktj3_gan_zhdhs != null) {
            stmt.bindString(25, jktj3_gan_zhdhs);
        }
 
        String jktj3_sen_xqjg = entity.getJktj3_sen_xqjg();
        if (jktj3_sen_xqjg != null) {
            stmt.bindString(26, jktj3_sen_xqjg);
        }
 
        String jktj3_sen_xnsd = entity.getJktj3_sen_xnsd();
        if (jktj3_sen_xnsd != null) {
            stmt.bindString(27, jktj3_sen_xnsd);
        }
 
        String jktj3_sen_xj = entity.getJktj3_sen_xj();
        if (jktj3_sen_xj != null) {
            stmt.bindString(28, jktj3_sen_xj);
        }
 
        String jktj3_sen_xn = entity.getJktj3_sen_xn();
        if (jktj3_sen_xn != null) {
            stmt.bindString(29, jktj3_sen_xn);
        }
 
        String jktj3_xz_zdgc = entity.getJktj3_xz_zdgc();
        if (jktj3_xz_zdgc != null) {
            stmt.bindString(30, jktj3_xz_zdgc);
        }
 
        String jktj3_xz_gysz = entity.getJktj3_xz_gysz();
        if (jktj3_xz_gysz != null) {
            stmt.bindString(31, jktj3_xz_gysz);
        }
 
        String jktj3_xz_dmd = entity.getJktj3_xz_dmd();
        if (jktj3_xz_dmd != null) {
            stmt.bindString(32, jktj3_xz_dmd);
        }
 
        String jktj3_xz_gmd = entity.getJktj3_xz_gmd();
        if (jktj3_xz_gmd != null) {
            stmt.bindString(33, jktj3_xz_gmd);
        }
        stmt.bindLong(34, entity.getJktj3_xb());
 
        String jktj3_xb_ms = entity.getJktj3_xb_ms();
        if (jktj3_xb_ms != null) {
            stmt.bindString(35, jktj3_xb_ms);
        }
        stmt.bindLong(36, entity.getJktj3_bc());
 
        String jktj3_bc_ms = entity.getJktj3_bc_ms();
        if (jktj3_bc_ms != null) {
            stmt.bindString(37, jktj3_bc_ms);
        }
        stmt.bindLong(38, entity.getJktj3_gj());
 
        String jktj3_gj_ms = entity.getJktj3_gj_ms();
        if (jktj3_gj_ms != null) {
            stmt.bindString(39, jktj3_gj_ms);
        }
 
        String jktj3_bz = entity.getJktj3_bz();
        if (jktj3_bz != null) {
            stmt.bindString(40, jktj3_bz);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(41, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public JianKangTiJianBiao_D readEntity(Cursor cursor, int offset) {
        JianKangTiJianBiao_D entity = new JianKangTiJianBiao_D( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // jktj3_id
            cursor.getString(offset + 2), // jktj_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // jktj3_xcg_xhdb
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // jktj3_xcg_bxb
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // jktj3_xcg_xxb
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // jktj3_xcg_other
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // jktj3_ncg_ndb
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // jktj3_ncg_nt
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // jktj3_ncg_ntt
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // jktj3_ncg_nqx
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // jktj3_ncg_other
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // jktj3_kfxt
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // jktj3_kfxt1
            cursor.getInt(offset + 14), // jktj3_xdt
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // jktj3_xdt_ms
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // jktj3_nwlbdb
            cursor.getInt(offset + 17), // jktj3_dbqx
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // jktj3_thxhdb
            cursor.getInt(offset + 19), // jktj3_yxgy
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // jktj3_gan_xqgb
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // jktj3_gan_xqgc
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // jktj3_gan_bdb
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // jktj3_gan_zdhs
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // jktj3_gan_zhdhs
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // jktj3_sen_xqjg
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // jktj3_sen_xnsd
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // jktj3_sen_xj
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // jktj3_sen_xn
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // jktj3_xz_zdgc
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // jktj3_xz_gysz
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // jktj3_xz_dmd
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // jktj3_xz_gmd
            cursor.getInt(offset + 33), // jktj3_xb
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // jktj3_xb_ms
            cursor.getInt(offset + 35), // jktj3_bc
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // jktj3_bc_ms
            cursor.getInt(offset + 37), // jktj3_gj
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // jktj3_gj_ms
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // jktj3_bz
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, JianKangTiJianBiao_D entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJktj3_id(cursor.getString(offset + 1));
        entity.setJktj_id(cursor.getString(offset + 2));
        entity.setJktj3_xcg_xhdb(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJktj3_xcg_bxb(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setJktj3_xcg_xxb(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setJktj3_xcg_other(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJktj3_ncg_ndb(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setJktj3_ncg_nt(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setJktj3_ncg_ntt(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setJktj3_ncg_nqx(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setJktj3_ncg_other(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setJktj3_kfxt(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setJktj3_kfxt1(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setJktj3_xdt(cursor.getInt(offset + 14));
        entity.setJktj3_xdt_ms(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setJktj3_nwlbdb(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setJktj3_dbqx(cursor.getInt(offset + 17));
        entity.setJktj3_thxhdb(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setJktj3_yxgy(cursor.getInt(offset + 19));
        entity.setJktj3_gan_xqgb(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setJktj3_gan_xqgc(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setJktj3_gan_bdb(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setJktj3_gan_zdhs(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setJktj3_gan_zhdhs(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setJktj3_sen_xqjg(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setJktj3_sen_xnsd(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setJktj3_sen_xj(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setJktj3_sen_xn(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setJktj3_xz_zdgc(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setJktj3_xz_gysz(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setJktj3_xz_dmd(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setJktj3_xz_gmd(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setJktj3_xb(cursor.getInt(offset + 33));
        entity.setJktj3_xb_ms(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setJktj3_bc(cursor.getInt(offset + 35));
        entity.setJktj3_bc_ms(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setJktj3_gj(cursor.getInt(offset + 37));
        entity.setJktj3_gj_ms(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setJktj3_bz(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setCreateDate(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(JianKangTiJianBiao_D entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(JianKangTiJianBiao_D entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(JianKangTiJianBiao_D entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
