package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.Province;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROVINCE".
*/
public class ProvinceDao extends AbstractDao<Province, Long> {

    public static final String TABLENAME = "PROVINCE";

    /**
     * Properties of entity Province.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Province_id = new Property(0, Long.class, "province_id", true, "_id");
        public final static Property Province_code = new Property(1, String.class, "province_code", false, "PROVINCE_CODE");
        public final static Property Province_name = new Property(2, String.class, "province_name", false, "PROVINCE_NAME");
        public final static Property CreateDate = new Property(3, String.class, "createDate", false, "CREATE_DATE");
    }


    public ProvinceDao(DaoConfig config) {
        super(config);
    }
    
    public ProvinceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROVINCE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: province_id
                "\"PROVINCE_CODE\" TEXT," + // 1: province_code
                "\"PROVINCE_NAME\" TEXT," + // 2: province_name
                "\"CREATE_DATE\" TEXT);"); // 3: createDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROVINCE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Province entity) {
        stmt.clearBindings();
 
        Long province_id = entity.getProvince_id();
        if (province_id != null) {
            stmt.bindLong(1, province_id);
        }
 
        String province_code = entity.getProvince_code();
        if (province_code != null) {
            stmt.bindString(2, province_code);
        }
 
        String province_name = entity.getProvince_name();
        if (province_name != null) {
            stmt.bindString(3, province_name);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(4, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Province entity) {
        stmt.clearBindings();
 
        Long province_id = entity.getProvince_id();
        if (province_id != null) {
            stmt.bindLong(1, province_id);
        }
 
        String province_code = entity.getProvince_code();
        if (province_code != null) {
            stmt.bindString(2, province_code);
        }
 
        String province_name = entity.getProvince_name();
        if (province_name != null) {
            stmt.bindString(3, province_name);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(4, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Province readEntity(Cursor cursor, int offset) {
        Province entity = new Province( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // province_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // province_code
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // province_name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Province entity, int offset) {
        entity.setProvince_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProvince_code(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setProvince_name(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreateDate(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Province entity, long rowId) {
        entity.setProvince_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Province entity) {
        if(entity != null) {
            return entity.getProvince_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Province entity) {
        return entity.getProvince_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
