package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.Xinshengerjitingfangshi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "XINSHENGERJITINGFANGSHI".
*/
public class XinshengerjitingfangshiDao extends AbstractDao<Xinshengerjitingfangshi, Long> {

    public static final String TABLENAME = "XINSHENGERJITINGFANGSHI";

    /**
     * Properties of entity Xinshengerjitingfangshi.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Xse_id = new Property(1, String.class, "xse_id", false, "XSE_ID");
        public final static Property Na_id = new Property(2, String.class, "na_id", false, "NA_ID");
        public final static Property Hw_id = new Property(3, String.class, "hw_id", false, "HW_ID");
        public final static Property Spo_id = new Property(4, String.class, "spo_id", false, "SPO_ID");
        public final static Property Cs_height = new Property(5, String.class, "cs_height", false, "CS_HEIGHT");
        public final static Property Temp_id = new Property(6, String.class, "temp_id", false, "TEMP_ID");
        public final static Property Xse_hxpl = new Property(7, String.class, "xse_hxpl", false, "XSE_HXPL");
        public final static Property Father_name = new Property(8, String.class, "father_name", false, "FATHER_NAME");
        public final static Property Father_pro = new Property(9, String.class, "father_pro", false, "FATHER_PRO");
        public final static Property Father_tel = new Property(10, String.class, "father_tel", false, "FATHER_TEL");
        public final static Property Father_bir = new Property(11, String.class, "father_bir", false, "FATHER_BIR");
        public final static Property Mother_name = new Property(12, String.class, "mother_name", false, "MOTHER_NAME");
        public final static Property Mother_pro = new Property(13, String.class, "mother_pro", false, "MOTHER_PRO");
        public final static Property Mother_tel = new Property(14, String.class, "mother_tel", false, "MOTHER_TEL");
        public final static Property Mother_bir = new Property(15, String.class, "mother_bir", false, "MOTHER_BIR");
        public final static Property Birth_week = new Property(16, String.class, "birth_week", false, "BIRTH_WEEK");
        public final static Property Mother_hbqk = new Property(17, int.class, "mother_hbqk", false, "MOTHER_HBQK");
        public final static Property Midwifery = new Property(18, String.class, "midwifery", false, "MIDWIFERY");
        public final static Property Birth_con = new Property(19, int.class, "birth_con", false, "BIRTH_CON");
        public final static Property Xse_asphyxia = new Property(20, int.class, "xse_asphyxia", false, "XSE_ASPHYXIA");
        public final static Property Apgar_score = new Property(21, int.class, "apgar_score", false, "APGAR_SCORE");
        public final static Property Xse_jix = new Property(22, int.class, "xse_jix", false, "XSE_JIX");
        public final static Property Jix_content = new Property(23, String.class, "jix_content", false, "JIX_CONTENT");
        public final static Property Xse_tlsc = new Property(24, int.class, "xse_tlsc", false, "XSE_TLSC");
        public final static Property Xse_jbsc = new Property(25, int.class, "xse_jbsc", false, "XSE_JBSC");
        public final static Property Xse_cstz = new Property(26, String.class, "xse_cstz", false, "XSE_CSTZ");
        public final static Property Xse_wyfs = new Property(27, int.class, "xse_wyfs", false, "XSE_WYFS");
        public final static Property Xse_chinl = new Property(28, String.class, "xse_chinl", false, "XSE_CHINL");
        public final static Property Xse_chincs = new Property(29, int.class, "xse_chincs", false, "XSE_CHINCS");
        public final static Property Xse_huxpl = new Property(30, int.class, "xse_huxpl", false, "XSE_HUXPL");
        public final static Property Xse_complexion = new Property(31, int.class, "xse_complexion", false, "XSE_COMPLEXION");
        public final static Property Xse_hdbw = new Property(32, int.class, "xse_hdbw", false, "XSE_HDBW");
        public final static Property Bregmatic1 = new Property(33, String.class, "bregmatic1", false, "BREGMATIC1");
        public final static Property Bregmatic2 = new Property(34, String.class, "bregmatic2", false, "BREGMATIC2");
        public final static Property Bregmatic_situa = new Property(35, int.class, "bregmatic_situa", false, "BREGMATIC_SITUA");
        public final static Property Eye_appearance = new Property(36, int.class, "eye_appearance", false, "EYE_APPEARANCE");
        public final static Property Yanwgnr = new Property(37, String.class, "yanwgnr", false, "YANWGNR");
        public final static Property Sizhdd = new Property(38, int.class, "sizhdd", false, "SIZHDD");
        public final static Property Sjzhddnr = new Property(39, String.class, "sjzhddnr", false, "SJZHDDNR");
        public final static Property Erwg = new Property(40, int.class, "erwg", false, "ERWG");
        public final static Property Erwgnr = new Property(41, String.class, "erwgnr", false, "ERWGNR");
        public final static Property Jingbbk = new Property(42, int.class, "jingbbk", false, "JINGBBK");
        public final static Property Xse_nose = new Property(43, int.class, "xse_nose", false, "XSE_NOSE");
        public final static Property Xse_skin = new Property(44, int.class, "xse_skin", false, "XSE_SKIN");
        public final static Property Oral_cavity = new Property(45, int.class, "oral_cavity", false, "ORAL_CAVITY");
        public final static Property Oral_cavitynr = new Property(46, String.class, "oral_cavitynr", false, "ORAL_CAVITYNR");
        public final static Property Xse_anus = new Property(47, int.class, "xse_anus", false, "XSE_ANUS");
        public final static Property Xse_anusnr = new Property(48, String.class, "xse_anusnr", false, "XSE_ANUSNR");
        public final static Property Xse_xftz = new Property(49, int.class, "xse_xftz", false, "XSE_XFTZ");
        public final static Property Xse_xftznr = new Property(50, String.class, "xse_xftznr", false, "XSE_XFTZNR");
        public final static Property Xse_wszq = new Property(51, int.class, "xse_wszq", false, "XSE_WSZQ");
        public final static Property Xse_wszqnr = new Property(52, String.class, "xse_wszqnr", false, "XSE_WSZQNR");
        public final static Property Xse_fbqz = new Property(53, int.class, "xse_fbqz", false, "XSE_FBQZ");
        public final static Property Xse_fbqznr = new Property(54, String.class, "xse_fbqznr", false, "XSE_FBQZNR");
        public final static Property Xse_jiz = new Property(55, int.class, "xse_jiz", false, "XSE_JIZ");
        public final static Property Xse_jiznr = new Property(56, String.class, "xse_jiznr", false, "XSE_JIZNR");
        public final static Property Xse_qid = new Property(57, int.class, "xse_qid", false, "XSE_QID");
        public final static Property Zhuanzjy = new Property(58, String.class, "zhuanzjy", false, "ZHUANZJY");
        public final static Property Zz_reason = new Property(59, String.class, "zz_reason", false, "ZZ_REASON");
        public final static Property Mechanism = new Property(60, String.class, "mechanism", false, "MECHANISM");
        public final static Property Guidance = new Property(61, int.class, "guidance", false, "GUIDANCE");
        public final static Property Xse_follow_date = new Property(62, String.class, "xse_follow_date", false, "XSE_FOLLOW_DATE");
        public final static Property Xse_follow_next = new Property(63, String.class, "xse_follow_next", false, "XSE_FOLLOW_NEXT");
        public final static Property Follow_site = new Property(64, String.class, "follow_site", false, "FOLLOW_SITE");
        public final static Property Xse_follow_doctor = new Property(65, String.class, "xse_follow_doctor", false, "XSE_FOLLOW_DOCTOR");
        public final static Property Xse_out = new Property(66, int.class, "xse_out", false, "XSE_OUT");
        public final static Property Xse_dab = new Property(67, int.class, "xse_dab", false, "XSE_DAB");
        public final static Property Xse_dabcs = new Property(68, int.class, "xse_dabcs", false, "XSE_DABCS");
        public final static Property Xse_nosenr = new Property(69, String.class, "xse_nosenr", false, "XSE_NOSENR");
        public final static Property Jingbbknr = new Property(70, String.class, "jingbbknr", false, "JINGBBKNR");
        public final static Property CreateDate = new Property(71, String.class, "createDate", false, "CREATE_DATE");
    }


    public XinshengerjitingfangshiDao(DaoConfig config) {
        super(config);
    }
    
    public XinshengerjitingfangshiDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"XINSHENGERJITINGFANGSHI\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"XSE_ID\" TEXT NOT NULL ," + // 1: xse_id
                "\"NA_ID\" TEXT," + // 2: na_id
                "\"HW_ID\" TEXT," + // 3: hw_id
                "\"SPO_ID\" TEXT," + // 4: spo_id
                "\"CS_HEIGHT\" TEXT," + // 5: cs_height
                "\"TEMP_ID\" TEXT," + // 6: temp_id
                "\"XSE_HXPL\" TEXT," + // 7: xse_hxpl
                "\"FATHER_NAME\" TEXT," + // 8: father_name
                "\"FATHER_PRO\" TEXT," + // 9: father_pro
                "\"FATHER_TEL\" TEXT," + // 10: father_tel
                "\"FATHER_BIR\" TEXT," + // 11: father_bir
                "\"MOTHER_NAME\" TEXT," + // 12: mother_name
                "\"MOTHER_PRO\" TEXT," + // 13: mother_pro
                "\"MOTHER_TEL\" TEXT," + // 14: mother_tel
                "\"MOTHER_BIR\" TEXT," + // 15: mother_bir
                "\"BIRTH_WEEK\" TEXT," + // 16: birth_week
                "\"MOTHER_HBQK\" INTEGER NOT NULL ," + // 17: mother_hbqk
                "\"MIDWIFERY\" TEXT," + // 18: midwifery
                "\"BIRTH_CON\" INTEGER NOT NULL ," + // 19: birth_con
                "\"XSE_ASPHYXIA\" INTEGER NOT NULL ," + // 20: xse_asphyxia
                "\"APGAR_SCORE\" INTEGER NOT NULL ," + // 21: apgar_score
                "\"XSE_JIX\" INTEGER NOT NULL ," + // 22: xse_jix
                "\"JIX_CONTENT\" TEXT," + // 23: jix_content
                "\"XSE_TLSC\" INTEGER NOT NULL ," + // 24: xse_tlsc
                "\"XSE_JBSC\" INTEGER NOT NULL ," + // 25: xse_jbsc
                "\"XSE_CSTZ\" TEXT," + // 26: xse_cstz
                "\"XSE_WYFS\" INTEGER NOT NULL ," + // 27: xse_wyfs
                "\"XSE_CHINL\" TEXT," + // 28: xse_chinl
                "\"XSE_CHINCS\" INTEGER NOT NULL ," + // 29: xse_chincs
                "\"XSE_HUXPL\" INTEGER NOT NULL ," + // 30: xse_huxpl
                "\"XSE_COMPLEXION\" INTEGER NOT NULL ," + // 31: xse_complexion
                "\"XSE_HDBW\" INTEGER NOT NULL ," + // 32: xse_hdbw
                "\"BREGMATIC1\" TEXT," + // 33: bregmatic1
                "\"BREGMATIC2\" TEXT," + // 34: bregmatic2
                "\"BREGMATIC_SITUA\" INTEGER NOT NULL ," + // 35: bregmatic_situa
                "\"EYE_APPEARANCE\" INTEGER NOT NULL ," + // 36: eye_appearance
                "\"YANWGNR\" TEXT," + // 37: yanwgnr
                "\"SIZHDD\" INTEGER NOT NULL ," + // 38: sizhdd
                "\"SJZHDDNR\" TEXT," + // 39: sjzhddnr
                "\"ERWG\" INTEGER NOT NULL ," + // 40: erwg
                "\"ERWGNR\" TEXT," + // 41: erwgnr
                "\"JINGBBK\" INTEGER NOT NULL ," + // 42: jingbbk
                "\"XSE_NOSE\" INTEGER NOT NULL ," + // 43: xse_nose
                "\"XSE_SKIN\" INTEGER NOT NULL ," + // 44: xse_skin
                "\"ORAL_CAVITY\" INTEGER NOT NULL ," + // 45: oral_cavity
                "\"ORAL_CAVITYNR\" TEXT," + // 46: oral_cavitynr
                "\"XSE_ANUS\" INTEGER NOT NULL ," + // 47: xse_anus
                "\"XSE_ANUSNR\" TEXT," + // 48: xse_anusnr
                "\"XSE_XFTZ\" INTEGER NOT NULL ," + // 49: xse_xftz
                "\"XSE_XFTZNR\" TEXT," + // 50: xse_xftznr
                "\"XSE_WSZQ\" INTEGER NOT NULL ," + // 51: xse_wszq
                "\"XSE_WSZQNR\" TEXT," + // 52: xse_wszqnr
                "\"XSE_FBQZ\" INTEGER NOT NULL ," + // 53: xse_fbqz
                "\"XSE_FBQZNR\" TEXT," + // 54: xse_fbqznr
                "\"XSE_JIZ\" INTEGER NOT NULL ," + // 55: xse_jiz
                "\"XSE_JIZNR\" TEXT," + // 56: xse_jiznr
                "\"XSE_QID\" INTEGER NOT NULL ," + // 57: xse_qid
                "\"ZHUANZJY\" TEXT," + // 58: zhuanzjy
                "\"ZZ_REASON\" TEXT," + // 59: zz_reason
                "\"MECHANISM\" TEXT," + // 60: mechanism
                "\"GUIDANCE\" INTEGER NOT NULL ," + // 61: guidance
                "\"XSE_FOLLOW_DATE\" TEXT," + // 62: xse_follow_date
                "\"XSE_FOLLOW_NEXT\" TEXT," + // 63: xse_follow_next
                "\"FOLLOW_SITE\" TEXT," + // 64: follow_site
                "\"XSE_FOLLOW_DOCTOR\" TEXT," + // 65: xse_follow_doctor
                "\"XSE_OUT\" INTEGER NOT NULL ," + // 66: xse_out
                "\"XSE_DAB\" INTEGER NOT NULL ," + // 67: xse_dab
                "\"XSE_DABCS\" INTEGER NOT NULL ," + // 68: xse_dabcs
                "\"XSE_NOSENR\" TEXT," + // 69: xse_nosenr
                "\"JINGBBKNR\" TEXT," + // 70: jingbbknr
                "\"CREATE_DATE\" TEXT);"); // 71: createDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"XINSHENGERJITINGFANGSHI\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Xinshengerjitingfangshi entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getXse_id());
 
        String na_id = entity.getNa_id();
        if (na_id != null) {
            stmt.bindString(3, na_id);
        }
 
        String hw_id = entity.getHw_id();
        if (hw_id != null) {
            stmt.bindString(4, hw_id);
        }
 
        String spo_id = entity.getSpo_id();
        if (spo_id != null) {
            stmt.bindString(5, spo_id);
        }
 
        String cs_height = entity.getCs_height();
        if (cs_height != null) {
            stmt.bindString(6, cs_height);
        }
 
        String temp_id = entity.getTemp_id();
        if (temp_id != null) {
            stmt.bindString(7, temp_id);
        }
 
        String xse_hxpl = entity.getXse_hxpl();
        if (xse_hxpl != null) {
            stmt.bindString(8, xse_hxpl);
        }
 
        String father_name = entity.getFather_name();
        if (father_name != null) {
            stmt.bindString(9, father_name);
        }
 
        String father_pro = entity.getFather_pro();
        if (father_pro != null) {
            stmt.bindString(10, father_pro);
        }
 
        String father_tel = entity.getFather_tel();
        if (father_tel != null) {
            stmt.bindString(11, father_tel);
        }
 
        String father_bir = entity.getFather_bir();
        if (father_bir != null) {
            stmt.bindString(12, father_bir);
        }
 
        String mother_name = entity.getMother_name();
        if (mother_name != null) {
            stmt.bindString(13, mother_name);
        }
 
        String mother_pro = entity.getMother_pro();
        if (mother_pro != null) {
            stmt.bindString(14, mother_pro);
        }
 
        String mother_tel = entity.getMother_tel();
        if (mother_tel != null) {
            stmt.bindString(15, mother_tel);
        }
 
        String mother_bir = entity.getMother_bir();
        if (mother_bir != null) {
            stmt.bindString(16, mother_bir);
        }
 
        String birth_week = entity.getBirth_week();
        if (birth_week != null) {
            stmt.bindString(17, birth_week);
        }
        stmt.bindLong(18, entity.getMother_hbqk());
 
        String midwifery = entity.getMidwifery();
        if (midwifery != null) {
            stmt.bindString(19, midwifery);
        }
        stmt.bindLong(20, entity.getBirth_con());
        stmt.bindLong(21, entity.getXse_asphyxia());
        stmt.bindLong(22, entity.getApgar_score());
        stmt.bindLong(23, entity.getXse_jix());
 
        String jix_content = entity.getJix_content();
        if (jix_content != null) {
            stmt.bindString(24, jix_content);
        }
        stmt.bindLong(25, entity.getXse_tlsc());
        stmt.bindLong(26, entity.getXse_jbsc());
 
        String xse_cstz = entity.getXse_cstz();
        if (xse_cstz != null) {
            stmt.bindString(27, xse_cstz);
        }
        stmt.bindLong(28, entity.getXse_wyfs());
 
        String xse_chinl = entity.getXse_chinl();
        if (xse_chinl != null) {
            stmt.bindString(29, xse_chinl);
        }
        stmt.bindLong(30, entity.getXse_chincs());
        stmt.bindLong(31, entity.getXse_huxpl());
        stmt.bindLong(32, entity.getXse_complexion());
        stmt.bindLong(33, entity.getXse_hdbw());
 
        String bregmatic1 = entity.getBregmatic1();
        if (bregmatic1 != null) {
            stmt.bindString(34, bregmatic1);
        }
 
        String bregmatic2 = entity.getBregmatic2();
        if (bregmatic2 != null) {
            stmt.bindString(35, bregmatic2);
        }
        stmt.bindLong(36, entity.getBregmatic_situa());
        stmt.bindLong(37, entity.getEye_appearance());
 
        String yanwgnr = entity.getYanwgnr();
        if (yanwgnr != null) {
            stmt.bindString(38, yanwgnr);
        }
        stmt.bindLong(39, entity.getSizhdd());
 
        String sjzhddnr = entity.getSjzhddnr();
        if (sjzhddnr != null) {
            stmt.bindString(40, sjzhddnr);
        }
        stmt.bindLong(41, entity.getErwg());
 
        String erwgnr = entity.getErwgnr();
        if (erwgnr != null) {
            stmt.bindString(42, erwgnr);
        }
        stmt.bindLong(43, entity.getJingbbk());
        stmt.bindLong(44, entity.getXse_nose());
        stmt.bindLong(45, entity.getXse_skin());
        stmt.bindLong(46, entity.getOral_cavity());
 
        String oral_cavitynr = entity.getOral_cavitynr();
        if (oral_cavitynr != null) {
            stmt.bindString(47, oral_cavitynr);
        }
        stmt.bindLong(48, entity.getXse_anus());
 
        String xse_anusnr = entity.getXse_anusnr();
        if (xse_anusnr != null) {
            stmt.bindString(49, xse_anusnr);
        }
        stmt.bindLong(50, entity.getXse_xftz());
 
        String xse_xftznr = entity.getXse_xftznr();
        if (xse_xftznr != null) {
            stmt.bindString(51, xse_xftznr);
        }
        stmt.bindLong(52, entity.getXse_wszq());
 
        String xse_wszqnr = entity.getXse_wszqnr();
        if (xse_wszqnr != null) {
            stmt.bindString(53, xse_wszqnr);
        }
        stmt.bindLong(54, entity.getXse_fbqz());
 
        String xse_fbqznr = entity.getXse_fbqznr();
        if (xse_fbqznr != null) {
            stmt.bindString(55, xse_fbqznr);
        }
        stmt.bindLong(56, entity.getXse_jiz());
 
        String xse_jiznr = entity.getXse_jiznr();
        if (xse_jiznr != null) {
            stmt.bindString(57, xse_jiznr);
        }
        stmt.bindLong(58, entity.getXse_qid());
 
        String zhuanzjy = entity.getZhuanzjy();
        if (zhuanzjy != null) {
            stmt.bindString(59, zhuanzjy);
        }
 
        String zz_reason = entity.getZz_reason();
        if (zz_reason != null) {
            stmt.bindString(60, zz_reason);
        }
 
        String mechanism = entity.getMechanism();
        if (mechanism != null) {
            stmt.bindString(61, mechanism);
        }
        stmt.bindLong(62, entity.getGuidance());
 
        String xse_follow_date = entity.getXse_follow_date();
        if (xse_follow_date != null) {
            stmt.bindString(63, xse_follow_date);
        }
 
        String xse_follow_next = entity.getXse_follow_next();
        if (xse_follow_next != null) {
            stmt.bindString(64, xse_follow_next);
        }
 
        String follow_site = entity.getFollow_site();
        if (follow_site != null) {
            stmt.bindString(65, follow_site);
        }
 
        String xse_follow_doctor = entity.getXse_follow_doctor();
        if (xse_follow_doctor != null) {
            stmt.bindString(66, xse_follow_doctor);
        }
        stmt.bindLong(67, entity.getXse_out());
        stmt.bindLong(68, entity.getXse_dab());
        stmt.bindLong(69, entity.getXse_dabcs());
 
        String xse_nosenr = entity.getXse_nosenr();
        if (xse_nosenr != null) {
            stmt.bindString(70, xse_nosenr);
        }
 
        String jingbbknr = entity.getJingbbknr();
        if (jingbbknr != null) {
            stmt.bindString(71, jingbbknr);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(72, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Xinshengerjitingfangshi entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getXse_id());
 
        String na_id = entity.getNa_id();
        if (na_id != null) {
            stmt.bindString(3, na_id);
        }
 
        String hw_id = entity.getHw_id();
        if (hw_id != null) {
            stmt.bindString(4, hw_id);
        }
 
        String spo_id = entity.getSpo_id();
        if (spo_id != null) {
            stmt.bindString(5, spo_id);
        }
 
        String cs_height = entity.getCs_height();
        if (cs_height != null) {
            stmt.bindString(6, cs_height);
        }
 
        String temp_id = entity.getTemp_id();
        if (temp_id != null) {
            stmt.bindString(7, temp_id);
        }
 
        String xse_hxpl = entity.getXse_hxpl();
        if (xse_hxpl != null) {
            stmt.bindString(8, xse_hxpl);
        }
 
        String father_name = entity.getFather_name();
        if (father_name != null) {
            stmt.bindString(9, father_name);
        }
 
        String father_pro = entity.getFather_pro();
        if (father_pro != null) {
            stmt.bindString(10, father_pro);
        }
 
        String father_tel = entity.getFather_tel();
        if (father_tel != null) {
            stmt.bindString(11, father_tel);
        }
 
        String father_bir = entity.getFather_bir();
        if (father_bir != null) {
            stmt.bindString(12, father_bir);
        }
 
        String mother_name = entity.getMother_name();
        if (mother_name != null) {
            stmt.bindString(13, mother_name);
        }
 
        String mother_pro = entity.getMother_pro();
        if (mother_pro != null) {
            stmt.bindString(14, mother_pro);
        }
 
        String mother_tel = entity.getMother_tel();
        if (mother_tel != null) {
            stmt.bindString(15, mother_tel);
        }
 
        String mother_bir = entity.getMother_bir();
        if (mother_bir != null) {
            stmt.bindString(16, mother_bir);
        }
 
        String birth_week = entity.getBirth_week();
        if (birth_week != null) {
            stmt.bindString(17, birth_week);
        }
        stmt.bindLong(18, entity.getMother_hbqk());
 
        String midwifery = entity.getMidwifery();
        if (midwifery != null) {
            stmt.bindString(19, midwifery);
        }
        stmt.bindLong(20, entity.getBirth_con());
        stmt.bindLong(21, entity.getXse_asphyxia());
        stmt.bindLong(22, entity.getApgar_score());
        stmt.bindLong(23, entity.getXse_jix());
 
        String jix_content = entity.getJix_content();
        if (jix_content != null) {
            stmt.bindString(24, jix_content);
        }
        stmt.bindLong(25, entity.getXse_tlsc());
        stmt.bindLong(26, entity.getXse_jbsc());
 
        String xse_cstz = entity.getXse_cstz();
        if (xse_cstz != null) {
            stmt.bindString(27, xse_cstz);
        }
        stmt.bindLong(28, entity.getXse_wyfs());
 
        String xse_chinl = entity.getXse_chinl();
        if (xse_chinl != null) {
            stmt.bindString(29, xse_chinl);
        }
        stmt.bindLong(30, entity.getXse_chincs());
        stmt.bindLong(31, entity.getXse_huxpl());
        stmt.bindLong(32, entity.getXse_complexion());
        stmt.bindLong(33, entity.getXse_hdbw());
 
        String bregmatic1 = entity.getBregmatic1();
        if (bregmatic1 != null) {
            stmt.bindString(34, bregmatic1);
        }
 
        String bregmatic2 = entity.getBregmatic2();
        if (bregmatic2 != null) {
            stmt.bindString(35, bregmatic2);
        }
        stmt.bindLong(36, entity.getBregmatic_situa());
        stmt.bindLong(37, entity.getEye_appearance());
 
        String yanwgnr = entity.getYanwgnr();
        if (yanwgnr != null) {
            stmt.bindString(38, yanwgnr);
        }
        stmt.bindLong(39, entity.getSizhdd());
 
        String sjzhddnr = entity.getSjzhddnr();
        if (sjzhddnr != null) {
            stmt.bindString(40, sjzhddnr);
        }
        stmt.bindLong(41, entity.getErwg());
 
        String erwgnr = entity.getErwgnr();
        if (erwgnr != null) {
            stmt.bindString(42, erwgnr);
        }
        stmt.bindLong(43, entity.getJingbbk());
        stmt.bindLong(44, entity.getXse_nose());
        stmt.bindLong(45, entity.getXse_skin());
        stmt.bindLong(46, entity.getOral_cavity());
 
        String oral_cavitynr = entity.getOral_cavitynr();
        if (oral_cavitynr != null) {
            stmt.bindString(47, oral_cavitynr);
        }
        stmt.bindLong(48, entity.getXse_anus());
 
        String xse_anusnr = entity.getXse_anusnr();
        if (xse_anusnr != null) {
            stmt.bindString(49, xse_anusnr);
        }
        stmt.bindLong(50, entity.getXse_xftz());
 
        String xse_xftznr = entity.getXse_xftznr();
        if (xse_xftznr != null) {
            stmt.bindString(51, xse_xftznr);
        }
        stmt.bindLong(52, entity.getXse_wszq());
 
        String xse_wszqnr = entity.getXse_wszqnr();
        if (xse_wszqnr != null) {
            stmt.bindString(53, xse_wszqnr);
        }
        stmt.bindLong(54, entity.getXse_fbqz());
 
        String xse_fbqznr = entity.getXse_fbqznr();
        if (xse_fbqznr != null) {
            stmt.bindString(55, xse_fbqznr);
        }
        stmt.bindLong(56, entity.getXse_jiz());
 
        String xse_jiznr = entity.getXse_jiznr();
        if (xse_jiznr != null) {
            stmt.bindString(57, xse_jiznr);
        }
        stmt.bindLong(58, entity.getXse_qid());
 
        String zhuanzjy = entity.getZhuanzjy();
        if (zhuanzjy != null) {
            stmt.bindString(59, zhuanzjy);
        }
 
        String zz_reason = entity.getZz_reason();
        if (zz_reason != null) {
            stmt.bindString(60, zz_reason);
        }
 
        String mechanism = entity.getMechanism();
        if (mechanism != null) {
            stmt.bindString(61, mechanism);
        }
        stmt.bindLong(62, entity.getGuidance());
 
        String xse_follow_date = entity.getXse_follow_date();
        if (xse_follow_date != null) {
            stmt.bindString(63, xse_follow_date);
        }
 
        String xse_follow_next = entity.getXse_follow_next();
        if (xse_follow_next != null) {
            stmt.bindString(64, xse_follow_next);
        }
 
        String follow_site = entity.getFollow_site();
        if (follow_site != null) {
            stmt.bindString(65, follow_site);
        }
 
        String xse_follow_doctor = entity.getXse_follow_doctor();
        if (xse_follow_doctor != null) {
            stmt.bindString(66, xse_follow_doctor);
        }
        stmt.bindLong(67, entity.getXse_out());
        stmt.bindLong(68, entity.getXse_dab());
        stmt.bindLong(69, entity.getXse_dabcs());
 
        String xse_nosenr = entity.getXse_nosenr();
        if (xse_nosenr != null) {
            stmt.bindString(70, xse_nosenr);
        }
 
        String jingbbknr = entity.getJingbbknr();
        if (jingbbknr != null) {
            stmt.bindString(71, jingbbknr);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(72, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Xinshengerjitingfangshi readEntity(Cursor cursor, int offset) {
        Xinshengerjitingfangshi entity = new Xinshengerjitingfangshi( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // xse_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // na_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // hw_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // spo_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // cs_height
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // temp_id
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // xse_hxpl
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // father_name
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // father_pro
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // father_tel
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // father_bir
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // mother_name
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // mother_pro
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // mother_tel
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // mother_bir
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // birth_week
            cursor.getInt(offset + 17), // mother_hbqk
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // midwifery
            cursor.getInt(offset + 19), // birth_con
            cursor.getInt(offset + 20), // xse_asphyxia
            cursor.getInt(offset + 21), // apgar_score
            cursor.getInt(offset + 22), // xse_jix
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // jix_content
            cursor.getInt(offset + 24), // xse_tlsc
            cursor.getInt(offset + 25), // xse_jbsc
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // xse_cstz
            cursor.getInt(offset + 27), // xse_wyfs
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // xse_chinl
            cursor.getInt(offset + 29), // xse_chincs
            cursor.getInt(offset + 30), // xse_huxpl
            cursor.getInt(offset + 31), // xse_complexion
            cursor.getInt(offset + 32), // xse_hdbw
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // bregmatic1
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // bregmatic2
            cursor.getInt(offset + 35), // bregmatic_situa
            cursor.getInt(offset + 36), // eye_appearance
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // yanwgnr
            cursor.getInt(offset + 38), // sizhdd
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // sjzhddnr
            cursor.getInt(offset + 40), // erwg
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // erwgnr
            cursor.getInt(offset + 42), // jingbbk
            cursor.getInt(offset + 43), // xse_nose
            cursor.getInt(offset + 44), // xse_skin
            cursor.getInt(offset + 45), // oral_cavity
            cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46), // oral_cavitynr
            cursor.getInt(offset + 47), // xse_anus
            cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48), // xse_anusnr
            cursor.getInt(offset + 49), // xse_xftz
            cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50), // xse_xftznr
            cursor.getInt(offset + 51), // xse_wszq
            cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52), // xse_wszqnr
            cursor.getInt(offset + 53), // xse_fbqz
            cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54), // xse_fbqznr
            cursor.getInt(offset + 55), // xse_jiz
            cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56), // xse_jiznr
            cursor.getInt(offset + 57), // xse_qid
            cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58), // zhuanzjy
            cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59), // zz_reason
            cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60), // mechanism
            cursor.getInt(offset + 61), // guidance
            cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62), // xse_follow_date
            cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63), // xse_follow_next
            cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64), // follow_site
            cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65), // xse_follow_doctor
            cursor.getInt(offset + 66), // xse_out
            cursor.getInt(offset + 67), // xse_dab
            cursor.getInt(offset + 68), // xse_dabcs
            cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69), // xse_nosenr
            cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70), // jingbbknr
            cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Xinshengerjitingfangshi entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setXse_id(cursor.getString(offset + 1));
        entity.setNa_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHw_id(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSpo_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCs_height(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTemp_id(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setXse_hxpl(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFather_name(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFather_pro(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setFather_tel(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFather_bir(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setMother_name(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setMother_pro(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setMother_tel(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setMother_bir(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setBirth_week(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setMother_hbqk(cursor.getInt(offset + 17));
        entity.setMidwifery(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setBirth_con(cursor.getInt(offset + 19));
        entity.setXse_asphyxia(cursor.getInt(offset + 20));
        entity.setApgar_score(cursor.getInt(offset + 21));
        entity.setXse_jix(cursor.getInt(offset + 22));
        entity.setJix_content(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setXse_tlsc(cursor.getInt(offset + 24));
        entity.setXse_jbsc(cursor.getInt(offset + 25));
        entity.setXse_cstz(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setXse_wyfs(cursor.getInt(offset + 27));
        entity.setXse_chinl(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setXse_chincs(cursor.getInt(offset + 29));
        entity.setXse_huxpl(cursor.getInt(offset + 30));
        entity.setXse_complexion(cursor.getInt(offset + 31));
        entity.setXse_hdbw(cursor.getInt(offset + 32));
        entity.setBregmatic1(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setBregmatic2(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setBregmatic_situa(cursor.getInt(offset + 35));
        entity.setEye_appearance(cursor.getInt(offset + 36));
        entity.setYanwgnr(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setSizhdd(cursor.getInt(offset + 38));
        entity.setSjzhddnr(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setErwg(cursor.getInt(offset + 40));
        entity.setErwgnr(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setJingbbk(cursor.getInt(offset + 42));
        entity.setXse_nose(cursor.getInt(offset + 43));
        entity.setXse_skin(cursor.getInt(offset + 44));
        entity.setOral_cavity(cursor.getInt(offset + 45));
        entity.setOral_cavitynr(cursor.isNull(offset + 46) ? null : cursor.getString(offset + 46));
        entity.setXse_anus(cursor.getInt(offset + 47));
        entity.setXse_anusnr(cursor.isNull(offset + 48) ? null : cursor.getString(offset + 48));
        entity.setXse_xftz(cursor.getInt(offset + 49));
        entity.setXse_xftznr(cursor.isNull(offset + 50) ? null : cursor.getString(offset + 50));
        entity.setXse_wszq(cursor.getInt(offset + 51));
        entity.setXse_wszqnr(cursor.isNull(offset + 52) ? null : cursor.getString(offset + 52));
        entity.setXse_fbqz(cursor.getInt(offset + 53));
        entity.setXse_fbqznr(cursor.isNull(offset + 54) ? null : cursor.getString(offset + 54));
        entity.setXse_jiz(cursor.getInt(offset + 55));
        entity.setXse_jiznr(cursor.isNull(offset + 56) ? null : cursor.getString(offset + 56));
        entity.setXse_qid(cursor.getInt(offset + 57));
        entity.setZhuanzjy(cursor.isNull(offset + 58) ? null : cursor.getString(offset + 58));
        entity.setZz_reason(cursor.isNull(offset + 59) ? null : cursor.getString(offset + 59));
        entity.setMechanism(cursor.isNull(offset + 60) ? null : cursor.getString(offset + 60));
        entity.setGuidance(cursor.getInt(offset + 61));
        entity.setXse_follow_date(cursor.isNull(offset + 62) ? null : cursor.getString(offset + 62));
        entity.setXse_follow_next(cursor.isNull(offset + 63) ? null : cursor.getString(offset + 63));
        entity.setFollow_site(cursor.isNull(offset + 64) ? null : cursor.getString(offset + 64));
        entity.setXse_follow_doctor(cursor.isNull(offset + 65) ? null : cursor.getString(offset + 65));
        entity.setXse_out(cursor.getInt(offset + 66));
        entity.setXse_dab(cursor.getInt(offset + 67));
        entity.setXse_dabcs(cursor.getInt(offset + 68));
        entity.setXse_nosenr(cursor.isNull(offset + 69) ? null : cursor.getString(offset + 69));
        entity.setJingbbknr(cursor.isNull(offset + 70) ? null : cursor.getString(offset + 70));
        entity.setCreateDate(cursor.isNull(offset + 71) ? null : cursor.getString(offset + 71));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Xinshengerjitingfangshi entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Xinshengerjitingfangshi entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Xinshengerjitingfangshi entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
