package com.example.administrator.biaozhunban.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.administrator.biaozhunban.greendao.entity.Yufangjiezhong;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "YUFANGJIEZHONG".
*/
public class YufangjiezhongDao extends AbstractDao<Yufangjiezhong, Long> {

    public static final String TABLENAME = "YUFANGJIEZHONG";

    /**
     * Properties of entity Yufangjiezhong.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Yfjz_id = new Property(1, String.class, "yfjz_id", false, "YFJZ_ID");
        public final static Property Na_id = new Property(2, String.class, "na_id", false, "NA_ID");
        public final static Property Yfjz_jhrxm = new Property(3, String.class, "yfjz_jhrxm", false, "YFJZ_JHRXM");
        public final static Property Yfjz_yetgx = new Property(4, String.class, "yfjz_yetgx", false, "YFJZ_YETGX");
        public final static Property Yfjz_lxfs = new Property(5, String.class, "yfjz_lxfs", false, "YFJZ_LXFS");
        public final static Property Yfjz_jtxzz = new Property(6, String.class, "yfjz_jtxzz", false, "YFJZ_JTXZZ");
        public final static Property Yfjz_hjtype = new Property(7, String.class, "yfjz_hjtype", false, "YFJZ_HJTYPE");
        public final static Property Yfjz_hjdz = new Property(8, String.class, "yfjz_hjdz", false, "YFJZ_HJDZ");
        public final static Property Yfjz_qrsj = new Property(9, String.class, "yfjz_qrsj", false, "YFJZ_QRSJ");
        public final static Property Yfjz_qcsj = new Property(10, String.class, "yfjz_qcsj", false, "YFJZ_QCSJ");
        public final static Property Yfjz_qcyy = new Property(11, String.class, "yfjz_qcyy", false, "YFJZ_QCYY");
        public final static Property Yfjz_ymyc = new Property(12, String.class, "yfjz_ymyc", false, "YFJZ_YMYC");
        public final static Property Yfjz_zhjj = new Property(13, String.class, "yfjz_zhjj", false, "YFJZ_ZHJJ");
        public final static Property Yfjz_crbs = new Property(14, String.class, "yfjz_crbs", false, "YFJZ_CRBS");
        public final static Property Yfjz_date = new Property(15, String.class, "yfjz_date", false, "YFJZ_DATE");
        public final static Property Yfjz_jkr = new Property(16, String.class, "yfjz_jkr", false, "YFJZ_JKR");
        public final static Property CreateDate = new Property(17, String.class, "createDate", false, "CREATE_DATE");
    }


    public YufangjiezhongDao(DaoConfig config) {
        super(config);
    }
    
    public YufangjiezhongDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"YUFANGJIEZHONG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"YFJZ_ID\" TEXT," + // 1: yfjz_id
                "\"NA_ID\" TEXT," + // 2: na_id
                "\"YFJZ_JHRXM\" TEXT," + // 3: yfjz_jhrxm
                "\"YFJZ_YETGX\" TEXT," + // 4: yfjz_yetgx
                "\"YFJZ_LXFS\" TEXT," + // 5: yfjz_lxfs
                "\"YFJZ_JTXZZ\" TEXT," + // 6: yfjz_jtxzz
                "\"YFJZ_HJTYPE\" TEXT," + // 7: yfjz_hjtype
                "\"YFJZ_HJDZ\" TEXT," + // 8: yfjz_hjdz
                "\"YFJZ_QRSJ\" TEXT," + // 9: yfjz_qrsj
                "\"YFJZ_QCSJ\" TEXT," + // 10: yfjz_qcsj
                "\"YFJZ_QCYY\" TEXT," + // 11: yfjz_qcyy
                "\"YFJZ_YMYC\" TEXT," + // 12: yfjz_ymyc
                "\"YFJZ_ZHJJ\" TEXT," + // 13: yfjz_zhjj
                "\"YFJZ_CRBS\" TEXT," + // 14: yfjz_crbs
                "\"YFJZ_DATE\" TEXT," + // 15: yfjz_date
                "\"YFJZ_JKR\" TEXT," + // 16: yfjz_jkr
                "\"CREATE_DATE\" TEXT);"); // 17: createDate
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_YUFANGJIEZHONG_YFJZ_ID ON \"YUFANGJIEZHONG\"" +
                " (\"YFJZ_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"YUFANGJIEZHONG\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Yufangjiezhong entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String yfjz_id = entity.getYfjz_id();
        if (yfjz_id != null) {
            stmt.bindString(2, yfjz_id);
        }
 
        String na_id = entity.getNa_id();
        if (na_id != null) {
            stmt.bindString(3, na_id);
        }
 
        String yfjz_jhrxm = entity.getYfjz_jhrxm();
        if (yfjz_jhrxm != null) {
            stmt.bindString(4, yfjz_jhrxm);
        }
 
        String yfjz_yetgx = entity.getYfjz_yetgx();
        if (yfjz_yetgx != null) {
            stmt.bindString(5, yfjz_yetgx);
        }
 
        String yfjz_lxfs = entity.getYfjz_lxfs();
        if (yfjz_lxfs != null) {
            stmt.bindString(6, yfjz_lxfs);
        }
 
        String yfjz_jtxzz = entity.getYfjz_jtxzz();
        if (yfjz_jtxzz != null) {
            stmt.bindString(7, yfjz_jtxzz);
        }
 
        String yfjz_hjtype = entity.getYfjz_hjtype();
        if (yfjz_hjtype != null) {
            stmt.bindString(8, yfjz_hjtype);
        }
 
        String yfjz_hjdz = entity.getYfjz_hjdz();
        if (yfjz_hjdz != null) {
            stmt.bindString(9, yfjz_hjdz);
        }
 
        String yfjz_qrsj = entity.getYfjz_qrsj();
        if (yfjz_qrsj != null) {
            stmt.bindString(10, yfjz_qrsj);
        }
 
        String yfjz_qcsj = entity.getYfjz_qcsj();
        if (yfjz_qcsj != null) {
            stmt.bindString(11, yfjz_qcsj);
        }
 
        String yfjz_qcyy = entity.getYfjz_qcyy();
        if (yfjz_qcyy != null) {
            stmt.bindString(12, yfjz_qcyy);
        }
 
        String yfjz_ymyc = entity.getYfjz_ymyc();
        if (yfjz_ymyc != null) {
            stmt.bindString(13, yfjz_ymyc);
        }
 
        String yfjz_zhjj = entity.getYfjz_zhjj();
        if (yfjz_zhjj != null) {
            stmt.bindString(14, yfjz_zhjj);
        }
 
        String yfjz_crbs = entity.getYfjz_crbs();
        if (yfjz_crbs != null) {
            stmt.bindString(15, yfjz_crbs);
        }
 
        String yfjz_date = entity.getYfjz_date();
        if (yfjz_date != null) {
            stmt.bindString(16, yfjz_date);
        }
 
        String yfjz_jkr = entity.getYfjz_jkr();
        if (yfjz_jkr != null) {
            stmt.bindString(17, yfjz_jkr);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(18, createDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Yufangjiezhong entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String yfjz_id = entity.getYfjz_id();
        if (yfjz_id != null) {
            stmt.bindString(2, yfjz_id);
        }
 
        String na_id = entity.getNa_id();
        if (na_id != null) {
            stmt.bindString(3, na_id);
        }
 
        String yfjz_jhrxm = entity.getYfjz_jhrxm();
        if (yfjz_jhrxm != null) {
            stmt.bindString(4, yfjz_jhrxm);
        }
 
        String yfjz_yetgx = entity.getYfjz_yetgx();
        if (yfjz_yetgx != null) {
            stmt.bindString(5, yfjz_yetgx);
        }
 
        String yfjz_lxfs = entity.getYfjz_lxfs();
        if (yfjz_lxfs != null) {
            stmt.bindString(6, yfjz_lxfs);
        }
 
        String yfjz_jtxzz = entity.getYfjz_jtxzz();
        if (yfjz_jtxzz != null) {
            stmt.bindString(7, yfjz_jtxzz);
        }
 
        String yfjz_hjtype = entity.getYfjz_hjtype();
        if (yfjz_hjtype != null) {
            stmt.bindString(8, yfjz_hjtype);
        }
 
        String yfjz_hjdz = entity.getYfjz_hjdz();
        if (yfjz_hjdz != null) {
            stmt.bindString(9, yfjz_hjdz);
        }
 
        String yfjz_qrsj = entity.getYfjz_qrsj();
        if (yfjz_qrsj != null) {
            stmt.bindString(10, yfjz_qrsj);
        }
 
        String yfjz_qcsj = entity.getYfjz_qcsj();
        if (yfjz_qcsj != null) {
            stmt.bindString(11, yfjz_qcsj);
        }
 
        String yfjz_qcyy = entity.getYfjz_qcyy();
        if (yfjz_qcyy != null) {
            stmt.bindString(12, yfjz_qcyy);
        }
 
        String yfjz_ymyc = entity.getYfjz_ymyc();
        if (yfjz_ymyc != null) {
            stmt.bindString(13, yfjz_ymyc);
        }
 
        String yfjz_zhjj = entity.getYfjz_zhjj();
        if (yfjz_zhjj != null) {
            stmt.bindString(14, yfjz_zhjj);
        }
 
        String yfjz_crbs = entity.getYfjz_crbs();
        if (yfjz_crbs != null) {
            stmt.bindString(15, yfjz_crbs);
        }
 
        String yfjz_date = entity.getYfjz_date();
        if (yfjz_date != null) {
            stmt.bindString(16, yfjz_date);
        }
 
        String yfjz_jkr = entity.getYfjz_jkr();
        if (yfjz_jkr != null) {
            stmt.bindString(17, yfjz_jkr);
        }
 
        String createDate = entity.getCreateDate();
        if (createDate != null) {
            stmt.bindString(18, createDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Yufangjiezhong readEntity(Cursor cursor, int offset) {
        Yufangjiezhong entity = new Yufangjiezhong( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // yfjz_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // na_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // yfjz_jhrxm
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // yfjz_yetgx
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // yfjz_lxfs
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // yfjz_jtxzz
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // yfjz_hjtype
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // yfjz_hjdz
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // yfjz_qrsj
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // yfjz_qcsj
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // yfjz_qcyy
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // yfjz_ymyc
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // yfjz_zhjj
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // yfjz_crbs
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // yfjz_date
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // yfjz_jkr
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17) // createDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Yufangjiezhong entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setYfjz_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNa_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setYfjz_jhrxm(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setYfjz_yetgx(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setYfjz_lxfs(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setYfjz_jtxzz(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setYfjz_hjtype(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setYfjz_hjdz(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setYfjz_qrsj(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setYfjz_qcsj(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setYfjz_qcyy(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setYfjz_ymyc(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setYfjz_zhjj(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setYfjz_crbs(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setYfjz_date(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setYfjz_jkr(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setCreateDate(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Yufangjiezhong entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Yufangjiezhong entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Yufangjiezhong entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
